/* © 2026 Claude Hecker — NIS2 Quick-Check — AGPL-3.0
   ================================================================
   NIS2 Quick-Check — Bewertungsdaten
   Eigenständiges, rein clientseitiges Tool. Kein Backend, keine
   Cloud-Abhängigkeit. Alle Inhalte unabhängig verfasst.

   Lokalisierbare Felder sind {de,en,fr,nl}-Objekte (siehe tl() in
   i18n.js). Eigennamen (Behörden, Gesetzestitel, CSIRT) bleiben als
   einzelner String, da sie i.d.R. nicht übersetzt werden.

   WICHTIG: Dieses Tool ersetzt keine Rechtsberatung. Der
   Umsetzungsstand der NIS2-Richtlinie ändert sich laufend pro
   Mitgliedsstaat — vor jeder Entscheidung die zuständige nationale
   Behörde konsultieren. Stand der Länderdaten: siehe COUNTRY_DATA_ASOF.
   ================================================================ */

const COUNTRY_DATA_ASOF = '2026-08-26';

// ─── 10 Domänen nach NIS2 Art. 21(2)(a)–(j), je 5 Fragen ──────────
const NIS2_DOMAINS = [
  {
    id: 'risk-policy', article: 'Art. 21(2)(a)', icon: '📋',
    name: { de: 'Risikoanalyse & Sicherheitskonzepte', en: 'Risk Analysis & Security Policies', fr: 'Analyse des risques & politiques de sécurité', nl: 'Risicoanalyse & beveiligingsbeleid' },
    shortName: { de: 'Risiko & Policy', en: 'Risk & Policy', fr: 'Risque & politique', nl: 'Risico & beleid' },
    description: { de: 'Konzepte zur Risikoanalyse und Sicherheit von Informationssystemen.', en: 'Policies on risk analysis and information system security.', fr: 'Politiques relatives à l\'analyse des risques et à la sécurité des systèmes d\'information.', nl: 'Beleid voor risicoanalyse en beveiliging van informatiesystemen.' },
    questions: [
      { id: 'rp-1', text: { de: 'Existiert ein von der Geschäftsleitung freigegebenes Informationssicherheitskonzept?', en: 'Does a management-approved information security policy exist?', fr: 'Existe-t-il une politique de sécurité de l\'information approuvée par la direction ?', nl: 'Bestaat er een door de directie goedgekeurd informatiebeveiligingsbeleid?' }, help: { de: 'Dokumentiert, freigegeben, kommuniziert, regelmäßig überprüft?', en: 'Documented, approved, communicated, regularly reviewed?', fr: 'Documentée, approuvée, communiquée, revue régulièrement ?', nl: 'Gedocumenteerd, goedgekeurd, gecommuniceerd, regelmatig herzien?' } },
      { id: 'rp-2', text: { de: 'Gibt es eine dokumentierte Risikoanalyse-Methodik (z. B. angelehnt an ISO 27005 oder BSI-Grundschutz)?', en: 'Is there a documented risk analysis methodology (e.g. based on ISO 27005)?', fr: 'Existe-t-il une méthodologie documentée d\'analyse des risques (p. ex. basée sur l\'ISO 27005) ?', nl: 'Is er een gedocumenteerde risicoanalysemethodiek (bijv. gebaseerd op ISO 27005)?' }, help: { de: 'Sind Identifikation, Bewertung und Behandlung von Risiken formalisiert?', en: 'Are risk identification, evaluation and treatment formalized?', fr: 'L\'identification, l\'évaluation et le traitement des risques sont-ils formalisés ?', nl: 'Zijn identificatie, beoordeling en behandeling van risico\'s geformaliseerd?' } },
      { id: 'rp-3', text: { de: 'Werden Risikoanalysen mindestens jährlich sowie bei wesentlichen Änderungen durchgeführt?', en: 'Are risk analyses performed at least annually and after significant changes?', fr: 'Les analyses de risques sont-elles réalisées au moins une fois par an et lors de changements majeurs ?', nl: 'Worden risicoanalyses minstens jaarlijks en bij ingrijpende wijzigingen uitgevoerd?' }, help: { de: 'Turnus, Umfang, Auslöser für eine Neubewertung.', en: 'Frequency, scope, triggers for reassessment.', fr: 'Fréquence, portée, déclencheurs de réévaluation.', nl: 'Frequentie, reikwijdte, triggers voor herbeoordeling.' } },
      { id: 'rp-4', text: { de: 'Existiert ein Risikobehandlungsplan mit benannten Verantwortlichen, Fristen und Nachverfolgung?', en: 'Is there a risk treatment plan with assigned owners, deadlines and tracking?', fr: 'Existe-t-il un plan de traitement des risques avec responsables désignés, délais et suivi ?', nl: 'Is er een risicobehandelplan met aangewezen eigenaren, termijnen en opvolging?' }, help: { de: 'Akzeptieren, Mindern, Übertragen, Vermeiden — dokumentierte Entscheidung je Risiko?', en: 'Accept, mitigate, transfer, avoid — documented decision per risk?', fr: 'Accepter, atténuer, transférer, éviter — décision documentée par risque ?', nl: 'Accepteren, verminderen, overdragen, vermijden — gedocumenteerde beslissing per risico?' } },
      { id: 'rp-5', text: { de: 'Werden Sicherheitskonzepte planmäßig und anlassbezogen aktualisiert?', en: 'Are security policies updated on a planned and ad-hoc basis?', fr: 'Les politiques de sécurité sont-elles mises à jour de manière planifiée et ponctuelle ?', nl: 'Worden beveiligingsbeleidsdocumenten gepland en naar aanleiding van gebeurtenissen bijgewerkt?' }, help: { de: 'Versionsverwaltung und Review-Zyklus der Dokumente.', en: 'Version control and review cycle of the documents.', fr: 'Gestion des versions et cycle de revue des documents.', nl: 'Versiebeheer en reviewcyclus van de documenten.' } },
    ],
  },
  {
    id: 'incident-handling', article: 'Art. 21(2)(b)', icon: '🚨',
    name: { de: 'Bewältigung von Sicherheitsvorfällen', en: 'Incident Handling', fr: 'Gestion des incidents', nl: 'Incidentafhandeling' },
    shortName: { de: 'Vorfälle', en: 'Incidents', fr: 'Incidents', nl: 'Incidenten' },
    description: { de: 'Erkennung, Reaktion, Meldung und Wiederherstellung bei Sicherheitsvorfällen.', en: 'Detection, response, reporting and recovery for security incidents.', fr: 'Détection, réponse, signalement et rétablissement en cas d\'incident de sécurité.', nl: 'Detectie, respons, melding en herstel bij beveiligingsincidenten.' },
    questions: [
      { id: 'ih-1', text: { de: 'Existiert ein formaler Incident-Response-Plan mit klaren Rollen und Eskalationswegen?', en: 'Is there a formal incident response plan with clear roles and escalation paths?', fr: 'Existe-t-il un plan formel de réponse aux incidents avec rôles et voies d\'escalade clairs ?', nl: 'Is er een formeel incident response plan met duidelijke rollen en escalatiepaden?' }, help: { de: 'Erkennung, Eindämmung, Beseitigung, Wiederherstellung, Nachbereitung.', en: 'Detection, containment, eradication, recovery, lessons learned.', fr: 'Détection, confinement, éradication, rétablissement, retour d\'expérience.', nl: 'Detectie, indamming, verwijdering, herstel, evaluatie.' } },
      { id: 'ih-2', text: { de: 'Sind automatisierte Erkennungs- und Monitoring-Fähigkeiten für kritische Systeme im Einsatz?', en: 'Are automated detection and monitoring capabilities deployed for critical systems?', fr: 'Des capacités automatisées de détection et de surveillance sont-elles déployées pour les systèmes critiques ?', nl: 'Zijn er geautomatiseerde detectie- en monitoringmogelijkheden voor kritieke systemen?' }, help: { de: 'SIEM, IDS/IPS, EDR, zentrales Logging.', en: 'SIEM, IDS/IPS, EDR, central logging.', fr: 'SIEM, IDS/IPS, EDR, journalisation centralisée.', nl: 'SIEM, IDS/IPS, EDR, centrale logging.' } },
      { id: 'ih-3', text: { de: 'Gibt es ein klar benanntes Incident-Response-Team mit definierter Erreichbarkeit?', en: 'Is there a clearly designated incident response team with defined reachability?', fr: 'Existe-t-il une équipe de réponse aux incidents clairement désignée avec une disponibilité définie ?', nl: 'Is er een duidelijk aangewezen incident response team met vastgestelde bereikbaarheid?' }, help: { de: 'CSIRT/CERT-Funktion oder gleichwertig, ggf. 24/7.', en: 'CSIRT/CERT function or equivalent, possibly 24/7.', fr: 'Fonction CSIRT/CERT ou équivalente, éventuellement 24/7.', nl: 'CSIRT/CERT-functie of gelijkwaardig, eventueel 24/7.' } },
      { id: 'ih-4', text: { de: 'Können die NIS2-Meldefristen eingehalten werden (24h Frühwarnung, 72h Meldung, 1 Monat Abschlussbericht)?', en: 'Can the NIS2 reporting timelines be met (24h early warning, 72h notification, 1-month final report)?', fr: 'Les délais de notification NIS2 peuvent-ils être respectés (24h alerte précoce, 72h notification, 1 mois rapport final) ?', nl: 'Kunnen de NIS2-meldtermijnen worden gehaald (24u vroegtijdige waarschuwing, 72u melding, 1 maand eindrapport)?' }, help: { de: 'Prozess zur verpflichtenden Meldung an die zuständige Behörde vorhanden?', en: 'Is there a process for mandatory reporting to the competent authority?', fr: 'Existe-t-il un processus de notification obligatoire à l\'autorité compétente ?', nl: 'Is er een proces voor verplichte melding aan de bevoegde autoriteit?' } },
      { id: 'ih-5', text: { de: 'Werden Vorfälle systematisch nachbereitet und die Erkenntnisse zur Verbesserung genutzt?', en: 'Are incidents systematically reviewed and lessons used for improvement?', fr: 'Les incidents font-ils l\'objet d\'un retour d\'expérience systématique utilisé pour l\'amélioration ?', nl: 'Worden incidenten systematisch geëvalueerd en inzichten gebruikt voor verbetering?' }, help: { de: 'Root-Cause-Analyse, Lessons Learned, Folgemaßnahmen.', en: 'Root cause analysis, lessons learned, follow-up actions.', fr: 'Analyse des causes profondes, retours d\'expérience, actions de suivi.', nl: 'Root-cause-analyse, geleerde lessen, vervolgacties.' } },
    ],
  },
  {
    id: 'business-continuity', article: 'Art. 21(2)(c)', icon: '🔄',
    name: { de: 'Aufrechterhaltung des Betriebs', en: 'Business Continuity & Crisis Management', fr: 'Continuité d\'activité & gestion de crise', nl: 'Bedrijfscontinuïteit & crisisbeheer' },
    shortName: { de: 'BCM & Krisenmanagement', en: 'Business Continuity', fr: 'Continuité d\'activité', nl: 'Bedrijfscontinuïteit' },
    description: { de: 'Business Continuity, Backup-Management, Notfallwiederherstellung, Krisenmanagement.', en: 'Business continuity, backup management, disaster recovery, crisis management.', fr: 'Continuité d\'activité, gestion des sauvegardes, reprise après sinistre, gestion de crise.', nl: 'Bedrijfscontinuïteit, back-upbeheer, disaster recovery, crisisbeheer.' },
    questions: [
      { id: 'bc-1', text: { de: 'Existiert ein getesteter Business-Continuity-Plan für alle kritischen Services?', en: 'Is there a tested business continuity plan for all critical services?', fr: 'Existe-t-il un plan de continuité d\'activité testé pour tous les services critiques ?', nl: 'Is er een geteste bedrijfscontinuïteitsplan voor alle kritieke diensten?' }, help: { de: 'Umfang, Dokumentation, Bezug zur Business Impact Analyse.', en: 'Scope, documentation, link to business impact analysis.', fr: 'Portée, documentation, lien avec l\'analyse d\'impact sur l\'activité.', nl: 'Reikwijdte, documentatie, koppeling met business impact analyse.' } },
      { id: 'bc-2', text: { de: 'Werden Backups regelmäßig erstellt, getestet und getrennt vom Produktivsystem aufbewahrt?', en: 'Are backups created regularly, tested and stored separately from production?', fr: 'Les sauvegardes sont-elles créées régulièrement, testées et stockées séparément de la production ?', nl: 'Worden back-ups regelmatig gemaakt, getest en gescheiden van het productiesysteem bewaard?' }, help: { de: '3-2-1-Regel, Offline-/Air-Gap-Kopie, Restore-Tests.', en: '3-2-1 rule, offline/air-gap copy, restore tests.', fr: 'Règle 3-2-1, copie hors ligne/air-gap, tests de restauration.', nl: '3-2-1-regel, offline/air-gap-kopie, hersteltests.' } },
      { id: 'bc-3', text: { de: 'Gibt es einen Disaster-Recovery-Plan mit definierten RTO-/RPO-Zielen?', en: 'Is there a disaster recovery plan with defined RTO/RPO targets?', fr: 'Existe-t-il un plan de reprise après sinistre avec des objectifs RTO/RPO définis ?', nl: 'Is er een disaster recovery plan met vastgestelde RTO-/RPO-doelen?' }, help: { de: 'Wiederherstellungszeit- und Datenverlust-Ziele je kritischem System.', en: 'Recovery time and data-loss targets per critical system.', fr: 'Objectifs de délai de récupération et de perte de données par système critique.', nl: 'Hersteltijd- en gegevensverliesdoelen per kritiek systeem.' } },
      { id: 'bc-4', text: { de: 'Existiert ein Krisenmanagement-Rahmenwerk mit definierten Eskalationsstufen?', en: 'Is there a crisis management framework with defined escalation levels?', fr: 'Existe-t-il un cadre de gestion de crise avec des niveaux d\'escalade définis ?', nl: 'Is er een crisisbeheerkader met vastgestelde escalatieniveaus?' }, help: { de: 'Krisenstab, Kommunikationswege, Entscheidungsbefugnisse.', en: 'Crisis team, communication channels, decision authority.', fr: 'Cellule de crise, canaux de communication, pouvoirs de décision.', nl: 'Crisisteam, communicatiekanalen, beslissingsbevoegdheden.' } },
      { id: 'bc-5', text: { de: 'Werden BCM-/DR-Pläne regelmäßig durch Übungen getestet?', en: 'Are BCM/DR plans regularly tested through exercises?', fr: 'Les plans PCA/PRA sont-ils régulièrement testés par des exercices ?', nl: 'Worden BCM-/DR-plannen regelmatig getest via oefeningen?' }, help: { de: 'Tabletop-Übungen, simulierte Ausfälle, dokumentierte Ergebnisse.', en: 'Tabletop exercises, simulated outages, documented results.', fr: 'Exercices sur table, pannes simulées, résultats documentés.', nl: 'Tabletop-oefeningen, gesimuleerde uitval, gedocumenteerde resultaten.' } },
    ],
  },
  {
    id: 'supply-chain', article: 'Art. 21(2)(d)', icon: '🔗',
    name: { de: 'Sicherheit der Lieferkette', en: 'Supply Chain Security', fr: 'Sécurité de la chaîne d\'approvisionnement', nl: 'Beveiliging van de toeleveringsketen' },
    shortName: { de: 'Lieferkette', en: 'Supply Chain', fr: 'Chaîne d\'approvisionnement', nl: 'Toeleveringsketen' },
    description: { de: 'Sicherheitsaspekte in Beziehungen zu direkten Lieferanten und Diensteanbietern.', en: 'Security aspects in relationships with direct suppliers and service providers.', fr: 'Aspects sécuritaires des relations avec les fournisseurs directs et prestataires de services.', nl: 'Beveiligingsaspecten in relaties met directe leveranciers en dienstverleners.' },
    questions: [
      { id: 'sc-1', text: { de: 'Werden Sicherheitsanforderungen vertraglich mit kritischen Lieferanten vereinbart?', en: 'Are security requirements contractually agreed with critical suppliers?', fr: 'Des exigences de sécurité sont-elles contractuellement convenues avec les fournisseurs critiques ?', nl: 'Worden beveiligingseisen contractueel vastgelegd met kritieke leveranciers?' }, help: { de: 'SLAs, Sicherheitsklauseln, Auditrechte.', en: 'SLAs, security clauses, audit rights.', fr: 'SLA, clauses de sécurité, droits d\'audit.', nl: 'SLA\'s, beveiligingsclausules, auditrechten.' } },
      { id: 'sc-2', text: { de: 'Erfolgt eine Risikobewertung von Lieferanten vor und während der Zusammenarbeit?', en: 'Are suppliers risk-assessed before and during the engagement?', fr: 'Une évaluation des risques des fournisseurs est-elle réalisée avant et pendant la collaboration ?', nl: 'Vindt er een risicobeoordeling van leveranciers plaats vóór en tijdens de samenwerking?' }, help: { de: 'Erstprüfung, wiederkehrende Bewertung, Eskalationspfad bei Auffälligkeiten.', en: 'Initial check, recurring assessment, escalation path for issues.', fr: 'Vérification initiale, évaluation récurrente, chemin d\'escalade en cas d\'anomalies.', nl: 'Initiële controle, terugkerende beoordeling, escalatiepad bij afwijkingen.' } },
      { id: 'sc-3', text: { de: 'Besteht ein Überblick über kritische Abhängigkeiten in der Lieferkette (inkl. Sub-Lieferanten)?', en: 'Is there an overview of critical supply chain dependencies (incl. sub-suppliers)?', fr: 'Existe-t-il une vue d\'ensemble des dépendances critiques de la chaîne (y compris sous-traitants) ?', nl: 'Is er een overzicht van kritieke afhankelijkheden in de keten (incl. onderaannemers)?' }, help: { de: 'Kartierung kritischer Systeme/Dienste und ihrer Herkunft.', en: 'Mapping of critical systems/services and their origin.', fr: 'Cartographie des systèmes/services critiques et de leur origine.', nl: 'In kaart brengen van kritieke systemen/diensten en hun herkomst.' } },
      { id: 'sc-4', text: { de: 'Werden Software-Lieferketten (z. B. Bibliotheken, Container-Images) auf bekannte Schwachstellen geprüft?', en: 'Are software supply chains (e.g. libraries, container images) checked for known vulnerabilities?', fr: 'Les chaînes logistiques logicielles (bibliothèques, images de conteneurs) sont-elles vérifiées contre les vulnérabilités connues ?', nl: 'Worden softwareketens (bijv. bibliotheken, containerimages) gecontroleerd op bekende kwetsbaarheden?' }, help: { de: 'SBOM, Dependency-Scanning, Patch-Management für Drittkomponenten.', en: 'SBOM, dependency scanning, patch management for third-party components.', fr: 'SBOM, analyse des dépendances, gestion des correctifs pour composants tiers.', nl: 'SBOM, dependency-scanning, patchbeheer voor componenten van derden.' } },
      { id: 'sc-5', text: { de: 'Gibt es einen Prozess für den Umgang mit Sicherheitsvorfällen bei Lieferanten?', en: 'Is there a process for handling security incidents at suppliers?', fr: 'Existe-t-il un processus de gestion des incidents de sécurité chez les fournisseurs ?', nl: 'Is er een proces voor het omgaan met beveiligingsincidenten bij leveranciers?' }, help: { de: 'Meldewege, vertragliche Informationspflichten, Notfallübernahme.', en: 'Reporting channels, contractual information duties, emergency takeover.', fr: 'Canaux de signalement, obligations d\'information contractuelles, reprise d\'urgence.', nl: 'Meldingskanalen, contractuele informatieverplichtingen, noodovername.' } },
    ],
  },
  {
    id: 'secure-development', article: 'Art. 21(2)(e)', icon: '🛠️',
    name: { de: 'Sicherheit bei Beschaffung, Entwicklung, Wartung', en: 'Security in Acquisition, Development & Maintenance', fr: 'Sécurité de l\'acquisition, du développement et de la maintenance', nl: 'Beveiliging bij verwerving, ontwikkeling en onderhoud' },
    shortName: { de: 'Entwicklung & Wartung', en: 'Development & Maintenance', fr: 'Développement & maintenance', nl: 'Ontwikkeling & onderhoud' },
    description: { de: 'Sicherheit von Netz- und Informationssystemen inkl. Schwachstellenmanagement.', en: 'Security of network and information systems incl. vulnerability management.', fr: 'Sécurité des systèmes de réseau et d\'information, y compris la gestion des vulnérabilités.', nl: 'Beveiliging van netwerk- en informatiesystemen incl. kwetsbaarhedenbeheer.' },
    questions: [
      { id: 'sd-1', text: { de: 'Existieren Sicherheitsanforderungen für Beschaffung und Entwicklung von IT-Systemen?', en: 'Do security requirements exist for the acquisition and development of IT systems?', fr: 'Existe-t-il des exigences de sécurité pour l\'acquisition et le développement des systèmes informatiques ?', nl: 'Bestaan er beveiligingseisen voor de verwerving en ontwikkeling van IT-systemen?' }, help: { de: 'Secure-by-Design-Prinzipien, Abnahmekriterien.', en: 'Secure-by-design principles, acceptance criteria.', fr: 'Principes de sécurité dès la conception, critères de réception.', nl: 'Secure-by-design-principes, acceptatiecriteria.' } },
      { id: 'sd-2', text: { de: 'Gibt es einen dokumentierten Schwachstellenmanagement-Prozess?', en: 'Is there a documented vulnerability management process?', fr: 'Existe-t-il un processus documenté de gestion des vulnérabilités ?', nl: 'Is er een gedocumenteerd kwetsbaarhedenbeheerproces?' }, help: { de: 'Erkennung, Bewertung (z. B. CVSS), priorisierte Behebung.', en: 'Detection, scoring (e.g. CVSS), prioritized remediation.', fr: 'Détection, notation (p. ex. CVSS), remédiation priorisée.', nl: 'Detectie, scoring (bijv. CVSS), geprioriteerde remediëring.' } },
      { id: 'sd-3', text: { de: 'Werden Patches für Betriebssysteme und Anwendungen zeitnah und geplant eingespielt?', en: 'Are patches for operating systems and applications applied promptly and on schedule?', fr: 'Les correctifs pour systèmes d\'exploitation et applications sont-ils déployés rapidement et selon un calendrier ?', nl: 'Worden patches voor besturingssystemen en applicaties tijdig en gepland toegepast?' }, help: { de: 'Patch-Zyklen, Notfall-Patches bei kritischen Schwachstellen.', en: 'Patch cycles, emergency patches for critical vulnerabilities.', fr: 'Cycles de correctifs, correctifs d\'urgence pour vulnérabilités critiques.', nl: 'Patchcycli, noodpatches voor kritieke kwetsbaarheden.' } },
      { id: 'sd-4', text: { de: 'Erfolgt eine sichere Konfiguration von Systemen nach dokumentierten Standards (Hardening)?', en: 'Are systems securely configured per documented standards (hardening)?', fr: 'Les systèmes sont-ils configurés de manière sécurisée selon des normes documentées (durcissement) ?', nl: 'Worden systemen veilig geconfigureerd volgens gedocumenteerde standaarden (hardening)?' }, help: { de: 'Baseline-Konfigurationen, Abweichungsprüfung.', en: 'Baseline configurations, deviation checks.', fr: 'Configurations de référence, contrôle des écarts.', nl: 'Baseline-configuraties, afwijkingscontrole.' } },
      { id: 'sd-5', text: { de: 'Werden Änderungen an produktiven Systemen über einen kontrollierten Change-Prozess freigegeben?', en: 'Are changes to production systems approved via a controlled change process?', fr: 'Les modifications des systèmes de production sont-elles approuvées via un processus de gestion du changement contrôlé ?', nl: 'Worden wijzigingen aan productiesystemen vrijgegeven via een beheerst wijzigingsproces?' }, help: { de: 'Testphase, Freigabe, Rollback-Möglichkeit.', en: 'Test phase, approval, rollback capability.', fr: 'Phase de test, approbation, possibilité de retour arrière.', nl: 'Testfase, goedkeuring, rollback-mogelijkheid.' } },
    ],
  },
  {
    id: 'effectiveness', article: 'Art. 21(2)(f)', icon: '📊',
    name: { de: 'Bewertung der Wirksamkeit', en: 'Effectiveness Assessment', fr: 'Évaluation de l\'efficacité', nl: 'Effectiviteitsbeoordeling' },
    shortName: { de: 'Wirksamkeitsprüfung', en: 'Effectiveness', fr: 'Efficacité', nl: 'Effectiviteit' },
    description: { de: 'Konzepte und Verfahren zur Bewertung der Wirksamkeit von Risikomanagementmaßnahmen.', en: 'Policies and procedures to assess the effectiveness of risk-management measures.', fr: 'Politiques et procédures d\'évaluation de l\'efficacité des mesures de gestion des risques.', nl: 'Beleid en procedures voor de beoordeling van de effectiviteit van risicobeheersmaatregelen.' },
    questions: [
      { id: 'ef-1', text: { de: 'Werden Sicherheitsmaßnahmen regelmäßig auf ihre Wirksamkeit hin überprüft?', en: 'Are security measures regularly reviewed for effectiveness?', fr: 'Les mesures de sécurité sont-elles régulièrement évaluées quant à leur efficacité ?', nl: 'Worden beveiligingsmaatregelen regelmatig op effectiviteit getoetst?' }, help: { de: 'Interne Audits, KPIs, Reifegradmessung.', en: 'Internal audits, KPIs, maturity measurement.', fr: 'Audits internes, KPI, mesure de maturité.', nl: 'Interne audits, KPI\'s, volwassenheidsmeting.' } },
      { id: 'ef-2', text: { de: 'Finden interne oder externe Sicherheitsaudits in regelmäßigen Abständen statt?', en: 'Do internal or external security audits take place at regular intervals?', fr: 'Des audits de sécurité internes ou externes ont-ils lieu à intervalles réguliers ?', nl: 'Vinden interne of externe beveiligingsaudits regelmatig plaats?' }, help: { de: 'Turnus, Umfang, Nachverfolgung von Feststellungen.', en: 'Frequency, scope, tracking of findings.', fr: 'Fréquence, portée, suivi des constatations.', nl: 'Frequentie, reikwijdte, opvolging van bevindingen.' } },
      { id: 'ef-3', text: { de: 'Werden Penetrationstests oder Schwachstellenscans regelmäßig durchgeführt?', en: 'Are penetration tests or vulnerability scans performed regularly?', fr: 'Des tests d\'intrusion ou des analyses de vulnérabilités sont-ils réalisés régulièrement ?', nl: 'Worden penetratietests of kwetsbaarheidsscans regelmatig uitgevoerd?' }, help: { de: 'Externe/interne Systeme, Häufigkeit, Nachverfolgung der Findings.', en: 'External/internal systems, frequency, tracking of findings.', fr: 'Systèmes externes/internes, fréquence, suivi des constatations.', nl: 'Externe/interne systemen, frequentie, opvolging van bevindingen.' } },
      { id: 'ef-4', text: { de: 'Existiert ein Berichtswesen an die Geschäftsleitung zum Sicherheitsstatus?', en: 'Is there reporting to management on the security status?', fr: 'Existe-t-il un reporting à la direction sur l\'état de la sécurité ?', nl: 'Is er rapportage aan de directie over de beveiligingsstatus?' }, help: { de: 'Regelmäßigkeit, Kennzahlen, Entscheidungsrelevanz.', en: 'Regularity, metrics, decision relevance.', fr: 'Régularité, indicateurs, pertinence décisionnelle.', nl: 'Regelmaat, kengetallen, besluitvormingsrelevantie.' } },
      { id: 'ef-5', text: { de: 'Werden Erkenntnisse aus Audits/Tests in einen nachverfolgten Maßnahmenplan überführt?', en: 'Are findings from audits/tests turned into a tracked action plan?', fr: 'Les constatations des audits/tests sont-elles converties en un plan d\'action suivi ?', nl: 'Worden bevindingen uit audits/tests omgezet in een opgevolgd actieplan?' }, help: { de: 'Verantwortliche, Fristen, Abschlussverfolgung.', en: 'Owners, deadlines, closure tracking.', fr: 'Responsables, délais, suivi de clôture.', nl: 'Eigenaren, termijnen, afsluitopvolging.' } },
    ],
  },
  {
    id: 'cyber-hygiene', article: 'Art. 21(2)(g)', icon: '🎓',
    name: { de: 'Cyberhygiene & Schulungen', en: 'Cyber Hygiene & Training', fr: 'Cyberhygiène & formation', nl: 'Cyberhygiëne & training' },
    shortName: { de: 'Awareness & Schulung', en: 'Awareness & Training', fr: 'Sensibilisation & formation', nl: 'Bewustwording & training' },
    description: { de: 'Grundlegende Verfahren der Cyberhygiene und Schulungen zur Cybersicherheit.', en: 'Basic cyber hygiene practices and cybersecurity training.', fr: 'Pratiques de base d\'hygiène informatique et formation à la cybersécurité.', nl: 'Basispraktijken voor cyberhygiëne en cyberbeveiligingstraining.' },
    questions: [
      { id: 'ch-1', text: { de: 'Erhalten alle Mitarbeitenden regelmäßige Sicherheits-Awareness-Schulungen?', en: 'Do all employees receive regular security awareness training?', fr: 'Tous les collaborateurs reçoivent-ils une formation régulière de sensibilisation à la sécurité ?', nl: 'Krijgen alle medewerkers regelmatig beveiligingsbewustzijnstraining?' }, help: { de: 'Turnus, Zielgruppen, Nachweis der Teilnahme.', en: 'Frequency, target groups, proof of attendance.', fr: 'Fréquence, publics cibles, preuve de participation.', nl: 'Frequentie, doelgroepen, bewijs van deelname.' } },
      { id: 'ch-2', text: { de: 'Erhält die Geschäftsleitung spezifische Schulungen zu Cybersicherheitsrisiken?', en: 'Does management receive specific training on cybersecurity risks?', fr: 'La direction reçoit-elle une formation spécifique sur les risques de cybersécurité ?', nl: 'Krijgt de directie specifieke training over cyberbeveiligingsrisico\'s?' }, help: { de: 'NIS2 fordert explizit Schulung des Leitungsorgans.', en: 'NIS2 explicitly requires training of the management body.', fr: 'NIS2 exige explicitement la formation de l\'organe de direction.', nl: 'NIS2 vereist expliciet training van het bestuursorgaan.' } },
      { id: 'ch-3', text: { de: 'Werden Phishing-Simulationen oder vergleichbare Awareness-Maßnahmen durchgeführt?', en: 'Are phishing simulations or comparable awareness measures conducted?', fr: 'Des simulations de phishing ou des mesures de sensibilisation comparables sont-elles menées ?', nl: 'Worden phishingsimulaties of vergelijkbare bewustwordingsmaatregelen uitgevoerd?' }, help: { de: 'Regelmäßigkeit, Auswertung, gezielte Nachschulung.', en: 'Frequency, evaluation, targeted follow-up training.', fr: 'Fréquence, évaluation, formation de suivi ciblée.', nl: 'Regelmaat, evaluatie, gerichte vervolgtraining.' } },
      { id: 'ch-4', text: { de: 'Existieren dokumentierte Richtlinien zu grundlegender Cyberhygiene (Passwörter, Geräte, Datenumgang)?', en: 'Are there documented policies on basic cyber hygiene (passwords, devices, data handling)?', fr: 'Existe-t-il des politiques documentées sur l\'hygiène informatique de base (mots de passe, appareils, gestion des données) ?', nl: 'Zijn er gedocumenteerde richtlijnen voor basiscyberhygiëne (wachtwoorden, apparaten, gegevensomgang)?' }, help: { de: 'Verständlich kommuniziert und durchsetzbar.', en: 'Clearly communicated and enforceable.', fr: 'Communiquées clairement et applicables.', nl: 'Duidelijk gecommuniceerd en afdwingbaar.' } },
      { id: 'ch-5', text: { de: 'Werden neue Mitarbeitende im Onboarding zu Sicherheitsthemen geschult?', en: 'Are new employees trained on security topics during onboarding?', fr: 'Les nouveaux collaborateurs sont-ils formés aux sujets de sécurité lors de leur intégration ?', nl: 'Worden nieuwe medewerkers tijdens onboarding getraind op beveiligingsonderwerpen?' }, help: { de: 'Fester Bestandteil des Einarbeitungsprozesses.', en: 'Fixed part of the onboarding process.', fr: 'Partie intégrante du processus d\'intégration.', nl: 'Vast onderdeel van het onboardingproces.' } },
    ],
  },
  {
    id: 'cryptography', article: 'Art. 21(2)(h)', icon: '🔐',
    name: { de: 'Kryptografie & Verschlüsselung', en: 'Cryptography & Encryption', fr: 'Cryptographie & chiffrement', nl: 'Cryptografie & versleuteling' },
    shortName: { de: 'Kryptografie', en: 'Cryptography', fr: 'Cryptographie', nl: 'Cryptografie' },
    description: { de: 'Konzepte und Verfahren für den Einsatz von Kryptografie und Verschlüsselung.', en: 'Policies and procedures for the use of cryptography and encryption.', fr: 'Politiques et procédures d\'utilisation de la cryptographie et du chiffrement.', nl: 'Beleid en procedures voor het gebruik van cryptografie en versleuteling.' },
    questions: [
      { id: 'cr-1', text: { de: 'Existiert eine dokumentierte Kryptografie-Richtlinie (zulässige Algorithmen, Schlüssellängen)?', en: 'Is there a documented cryptography policy (allowed algorithms, key lengths)?', fr: 'Existe-t-il une politique cryptographique documentée (algorithmes autorisés, longueurs de clés) ?', nl: 'Is er een gedocumenteerd cryptografiebeleid (toegestane algoritmen, sleutellengtes)?' }, help: { de: 'Aktueller Stand der Technik, regelmäßige Überprüfung.', en: 'Current state of the art, regular review.', fr: 'État de l\'art actuel, revue régulière.', nl: 'Actuele stand der techniek, regelmatige herziening.' } },
      { id: 'cr-2', text: { de: 'Werden Daten bei der Übertragung durchgängig verschlüsselt (z. B. TLS)?', en: 'Is data consistently encrypted in transit (e.g. TLS)?', fr: 'Les données sont-elles systématiquement chiffrées en transit (p. ex. TLS) ?', nl: 'Worden gegevens consequent versleuteld tijdens verzending (bijv. TLS)?' }, help: { de: 'Interne und externe Kommunikationswege.', en: 'Internal and external communication channels.', fr: 'Canaux de communication internes et externes.', nl: 'Interne en externe communicatiekanalen.' } },
      { id: 'cr-3', text: { de: 'Werden sensible Daten auch im Ruhezustand verschlüsselt (Encryption at Rest)?', en: 'Is sensitive data also encrypted at rest?', fr: 'Les données sensibles sont-elles également chiffrées au repos ?', nl: 'Worden gevoelige gegevens ook versleuteld in rust (encryption at rest)?' }, help: { de: 'Datenbanken, Backups, mobile Datenträger.', en: 'Databases, backups, mobile storage media.', fr: 'Bases de données, sauvegardes, supports mobiles.', nl: 'Databases, back-ups, mobiele gegevensdragers.' } },
      { id: 'cr-4', text: { de: 'Existiert ein Schlüsselmanagement-Prozess (Erzeugung, Rotation, Widerruf)?', en: 'Is there a key management process (generation, rotation, revocation)?', fr: 'Existe-t-il un processus de gestion des clés (génération, rotation, révocation) ?', nl: 'Is er een sleutelbeheerproces (genereren, roteren, intrekken)?' }, help: { de: 'Zentrale Verwaltung, definierte Verantwortlichkeiten.', en: 'Central administration, defined responsibilities.', fr: 'Administration centralisée, responsabilités définies.', nl: 'Centraal beheer, vastgestelde verantwoordelijkheden.' } },
      { id: 'cr-5', text: { de: 'Werden veraltete oder unsichere kryptografische Verfahren aktiv identifiziert und abgelöst?', en: 'Are outdated or insecure cryptographic methods actively identified and phased out?', fr: 'Les méthodes cryptographiques obsolètes ou non sécurisées sont-elles activement identifiées et abandonnées ?', nl: 'Worden verouderde of onveilige cryptografische methoden actief geïdentificeerd en uitgefaseerd?' }, help: { de: 'Inventarisierung, Migrationsplan.', en: 'Inventory, migration plan.', fr: 'Inventaire, plan de migration.', nl: 'Inventarisatie, migratieplan.' } },
    ],
  },
  {
    id: 'access-hr-asset', article: 'Art. 21(2)(i)', icon: '🔑',
    name: { de: 'Personalsicherheit, Zugriffskontrolle, Asset-Management', en: 'HR Security, Access Control & Asset Management', fr: 'Sécurité RH, contrôle d\'accès & gestion des actifs', nl: 'Personeelsbeveiliging, toegangscontrole & assetbeheer' },
    shortName: { de: 'Personal & Zugriff', en: 'HR & Access', fr: 'RH & accès', nl: 'Personeel & toegang' },
    description: { de: 'Personalsicherheit, Konzepte für die Zugriffskontrolle und das Asset-Management.', en: 'Human resources security, access control and asset management policies.', fr: 'Sécurité des ressources humaines, politiques de contrôle d\'accès et de gestion des actifs.', nl: 'Personeelsbeveiliging, toegangscontrole- en assetbeheerbeleid.' },
    questions: [
      { id: 'ha-1', text: { de: 'Existiert ein vollständiges Inventar aller IT-Assets (Hardware, Software, Daten)?', en: 'Is there a complete inventory of all IT assets (hardware, software, data)?', fr: 'Existe-t-il un inventaire complet de tous les actifs informatiques (matériel, logiciels, données) ?', nl: 'Is er een volledige inventaris van alle IT-assets (hardware, software, data)?' }, help: { de: 'Aktualität, Verantwortlichkeiten, Kritikalitätseinstufung.', en: 'Currency, ownership, criticality classification.', fr: 'Actualité, responsabilités, classification de criticité.', nl: 'Actualiteit, verantwoordelijkheden, criticaliteitsclassificatie.' } },
      { id: 'ha-2', text: { de: 'Werden Zugriffsrechte nach dem Prinzip der geringsten Berechtigung vergeben?', en: 'Are access rights granted according to the least-privilege principle?', fr: 'Les droits d\'accès sont-ils accordés selon le principe du moindre privilège ?', nl: 'Worden toegangsrechten toegekend volgens het principe van minimale rechten?' }, help: { de: 'Rollenbasierte Vergabe, regelmäßige Rezertifizierung.', en: 'Role-based assignment, regular recertification.', fr: 'Attribution basée sur les rôles, recertification régulière.', nl: 'Rolgebaseerde toewijzing, regelmatige herbeoordeling.' } },
      { id: 'ha-3', text: { de: 'Werden Zugriffsrechte beim Ausscheiden oder Rollenwechsel zeitnah entzogen/angepasst?', en: 'Are access rights revoked/adjusted promptly on departure or role change?', fr: 'Les droits d\'accès sont-ils révoqués/ajustés rapidement en cas de départ ou de changement de rôle ?', nl: 'Worden toegangsrechten tijdig ingetrokken/aangepast bij vertrek of functiewijziging?' }, help: { de: 'Definierter Offboarding-/Transfer-Prozess.', en: 'Defined offboarding/transfer process.', fr: 'Processus défini de départ/mutation.', nl: 'Vastgesteld offboarding-/overplaatsingsproces.' } },
      { id: 'ha-4', text: { de: 'Erfolgt eine Überprüfung von Personal in sicherheitsrelevanten Positionen (Background-Check)?', en: 'Is personnel in security-relevant positions vetted (background check)?', fr: 'Le personnel occupant des postes sensibles fait-il l\'objet d\'une vérification (contrôle d\'antécédents) ?', nl: 'Wordt personeel in beveiligingsrelevante posities gescreend (background check)?' }, help: { de: 'Im Rahmen der rechtlichen Möglichkeiten, risikobasiert.', en: 'Within legal limits, risk-based.', fr: 'Dans les limites légales, basé sur le risque.', nl: 'Binnen de wettelijke mogelijkheden, risicogebaseerd.' } },
      { id: 'ha-5', text: { de: 'Werden privilegierte Konten (Admin-Zugänge) besonders abgesichert und überwacht?', en: 'Are privileged accounts (admin access) specifically secured and monitored?', fr: 'Les comptes privilégiés (accès administrateur) sont-ils spécifiquement sécurisés et surveillés ?', nl: 'Worden bevoorrechte accounts (adminaccess) specifiek beveiligd en gemonitord?' }, help: { de: 'Getrennte Admin-Accounts, Protokollierung, ggf. PAM-Lösung.', en: 'Separate admin accounts, logging, possibly PAM solution.', fr: 'Comptes admin séparés, journalisation, éventuellement solution PAM.', nl: 'Gescheiden adminaccounts, logging, eventueel PAM-oplossing.' } },
    ],
  },
  {
    id: 'mfa-comms', article: 'Art. 21(2)(j)', icon: '📡',
    name: { de: 'MFA & Sichere Kommunikation', en: 'MFA & Secure Communications', fr: 'MFA & communications sécurisées', nl: 'MFA & beveiligde communicatie' },
    shortName: { de: 'MFA & Kommunikation', en: 'MFA & Communication', fr: 'MFA & communication', nl: 'MFA & communicatie' },
    description: { de: 'Einsatz von Mehrfaktor-Authentifizierung und gesicherter Sprach-/Video-/Textkommunikation.', en: 'Use of multi-factor authentication and secured voice/video/text communication.', fr: 'Utilisation de l\'authentification multifacteur et de communications vocales/vidéo/texte sécurisées.', nl: 'Gebruik van multifactorauthenticatie en beveiligde spraak-/video-/tekstcommunicatie.' },
    questions: [
      { id: 'mc-1', text: { de: 'Ist Mehrfaktor-Authentifizierung (MFA) für kritische Systeme und Fernzugriffe verpflichtend?', en: 'Is multi-factor authentication (MFA) mandatory for critical systems and remote access?', fr: 'L\'authentification multifacteur (MFA) est-elle obligatoire pour les systèmes critiques et les accès distants ?', nl: 'Is multifactorauthenticatie (MFA) verplicht voor kritieke systemen en toegang op afstand?' }, help: { de: 'VPN, Admin-Zugänge, Cloud-Dienste.', en: 'VPN, admin access, cloud services.', fr: 'VPN, accès administrateur, services cloud.', nl: 'VPN, adminaccess, clouddiensten.' } },
      { id: 'mc-2', text: { de: 'Ist MFA auch für E-Mail- und Kollaborationsdienste aktiviert?', en: 'Is MFA also enabled for email and collaboration services?', fr: 'La MFA est-elle également activée pour les services de messagerie et de collaboration ?', nl: 'Is MFA ook ingeschakeld voor e-mail- en samenwerkingsdiensten?' }, help: { de: 'Häufigstes Einfallstor — Standardabsicherung vorhanden?', en: 'Most common attack vector — is default protection in place?', fr: 'Vecteur d\'attaque le plus courant — la protection par défaut est-elle en place ?', nl: 'Meest voorkomende aanvalsvector — is standaardbescherming aanwezig?' } },
      { id: 'mc-3', text: { de: 'Existieren gesicherte Kommunikationswege für Notfälle (z. B. bei kompromittierter Infrastruktur)?', en: 'Do secured communication channels exist for emergencies (e.g. compromised infrastructure)?', fr: 'Existe-t-il des canaux de communication sécurisés pour les urgences (p. ex. infrastructure compromise) ?', nl: 'Bestaan er beveiligde communicatiekanalen voor noodgevallen (bijv. gecompromitteerde infrastructuur)?' }, help: { de: 'Out-of-Band-Kommunikation für den Krisenfall.', en: 'Out-of-band communication for crisis situations.', fr: 'Communication hors bande pour les situations de crise.', nl: 'Out-of-band-communicatie voor crisissituaties.' } },
      { id: 'mc-4', text: { de: 'Werden Sprach-/Video-Kommunikationssysteme nach Sicherheitsstandards abgesichert?', en: 'Are voice/video communication systems secured to security standards?', fr: 'Les systèmes de communication vocale/vidéo sont-ils sécurisés selon des normes de sécurité ?', nl: 'Worden spraak-/videocommunicatiesystemen beveiligd volgens beveiligingsnormen?' }, help: { de: 'Verschlüsselung, Zugriffsschutz bei Konferenzsystemen.', en: 'Encryption, access protection for conferencing systems.', fr: 'Chiffrement, protection d\'accès pour les systèmes de conférence.', nl: 'Versleuteling, toegangsbeveiliging voor conferentiesystemen.' } },
      { id: 'mc-5', text: { de: 'Existiert ein Notfallzugriffs-Verfahren, falls MFA-Faktoren nicht verfügbar sind?', en: 'Is there an emergency access procedure if MFA factors are unavailable?', fr: 'Existe-t-il une procédure d\'accès d\'urgence si les facteurs MFA sont indisponibles ?', nl: 'Is er een noodtoegangsprocedure als MFA-factoren niet beschikbaar zijn?' }, help: { de: 'Break-Glass-Verfahren mit Protokollierung, kein dauerhafter Bypass.', en: 'Break-glass procedure with logging, not a permanent bypass.', fr: 'Procédure "break-glass" avec journalisation, pas de contournement permanent.', nl: '"Break-glass"-procedure met logging, geen permanente omzeiling.' } },
    ],
  },
];

// ─── Reifegrad-Skala ────────────────────────────────────────────
const MATURITY_LEVELS = [
  { value: 0, color: '#dc2626', label: { de: 'Nicht umgesetzt', en: 'Not implemented', fr: 'Non mis en œuvre', nl: 'Niet geïmplementeerd' }, short: { de: 'Keine', en: 'None', fr: 'Aucune', nl: 'Geen' } },
  { value: 1, color: '#ea580c', label: { de: 'Ansatzweise / geplant', en: 'Basic / planned', fr: 'Amorcé / planifié', nl: 'Basaal / gepland' }, short: { de: 'Geplant', en: 'Planned', fr: 'Planifié', nl: 'Gepland' } },
  { value: 2, color: '#eab308', label: { de: 'Teilweise umgesetzt', en: 'Partially implemented', fr: 'Partiellement mis en œuvre', nl: 'Gedeeltelijk geïmplementeerd' }, short: { de: 'Teilweise', en: 'Partial', fr: 'Partiel', nl: 'Gedeeltelijk' } },
  { value: 3, color: '#84cc16', label: { de: 'Weitgehend umgesetzt', en: 'Largely implemented', fr: 'Largement mis en œuvre', nl: 'Grotendeels geïmplementeerd' }, short: { de: 'Weitgehend', en: 'Largely', fr: 'Largement', nl: 'Grotendeels' } },
  { value: 4, color: '#16a34a', label: { de: 'Vollständig umgesetzt & etabliert', en: 'Fully implemented & established', fr: 'Entièrement mis en œuvre & établi', nl: 'Volledig geïmplementeerd & geborgd' }, short: { de: 'Vollständig', en: 'Full', fr: 'Complet', nl: 'Volledig' } },
];

// ─── Sektor-Klassifizierung (vereinfacht, Anhang I/II NIS2) ────────
const SECTORS = [
  { id: 'energy', category: 'essential', name: { de: 'Energie', en: 'Energy', fr: 'Énergie', nl: 'Energie' } },
  { id: 'transport', category: 'essential', name: { de: 'Verkehr', en: 'Transport', fr: 'Transport', nl: 'Vervoer' } },
  { id: 'banking', category: 'essential', name: { de: 'Bankwesen', en: 'Banking', fr: 'Secteur bancaire', nl: 'Bankwezen' } },
  { id: 'financial-market', category: 'essential', name: { de: 'Finanzmarktinfrastruktur', en: 'Financial market infrastructure', fr: 'Infrastructure des marchés financiers', nl: 'Infrastructuur financiële markten' } },
  { id: 'health', category: 'essential', name: { de: 'Gesundheitswesen', en: 'Health', fr: 'Santé', nl: 'Gezondheidszorg' } },
  { id: 'water', category: 'essential', name: { de: 'Trinkwasser', en: 'Drinking water', fr: 'Eau potable', nl: 'Drinkwater' } },
  { id: 'wastewater', category: 'essential', name: { de: 'Abwasser', en: 'Waste water', fr: 'Eaux usées', nl: 'Afvalwater' } },
  { id: 'digital-infra', category: 'essential', name: { de: 'Digitale Infrastruktur', en: 'Digital infrastructure', fr: 'Infrastructure numérique', nl: 'Digitale infrastructuur' } },
  { id: 'ict-management', category: 'essential', name: { de: 'ICT-Dienstleistungsmanagement (B2B)', en: 'ICT service management (B2B)', fr: 'Gestion des services TIC (B2B)', nl: 'ICT-dienstenbeheer (B2B)' } },
  { id: 'public-admin', category: 'essential', name: { de: 'Öffentliche Verwaltung', en: 'Public administration', fr: 'Administration publique', nl: 'Overheidsadministratie' } },
  { id: 'space', category: 'essential', name: { de: 'Weltraum', en: 'Space', fr: 'Espace', nl: 'Ruimtevaart' } },
  { id: 'postal', category: 'important', name: { de: 'Post- und Kurierdienste', en: 'Postal and courier services', fr: 'Services postaux et d\'expédition', nl: 'Post- en koeriersdiensten' } },
  { id: 'waste', category: 'important', name: { de: 'Abfallbewirtschaftung', en: 'Waste management', fr: 'Gestion des déchets', nl: 'Afvalbeheer' } },
  { id: 'chemicals', category: 'important', name: { de: 'Herstellung/Handel mit Chemikalien', en: 'Manufacture/trade of chemicals', fr: 'Fabrication/commerce de produits chimiques', nl: 'Productie/handel in chemicaliën' } },
  { id: 'food', category: 'important', name: { de: 'Produktion/Verarbeitung/Vertrieb von Lebensmitteln', en: 'Production/processing/distribution of food', fr: 'Production/transformation/distribution alimentaire', nl: 'Productie/verwerking/distributie van levensmiddelen' } },
  { id: 'manufacturing', category: 'important', name: { de: 'Verarbeitendes Gewerbe (Medizinprodukte, Elektronik, Maschinenbau, Fahrzeugbau)', en: 'Manufacturing (medical devices, electronics, machinery, vehicles)', fr: 'Industrie manufacturière (dispositifs médicaux, électronique, machines, véhicules)', nl: 'Verwerkende industrie (medische hulpmiddelen, elektronica, machinebouw, voertuigen)' } },
  { id: 'digital-providers', category: 'important', name: { de: 'Anbieter digitaler Dienste (Marktplätze, Suchmaschinen, soziale Netzwerke)', en: 'Digital service providers (marketplaces, search engines, social networks)', fr: 'Fournisseurs de services numériques (marketplaces, moteurs de recherche, réseaux sociaux)', nl: 'Aanbieders van digitale diensten (marktplaatsen, zoekmachines, sociale netwerken)' } },
  { id: 'research', category: 'important', name: { de: 'Forschung', en: 'Research', fr: 'Recherche', nl: 'Onderzoek' } },
];

// ─── Länder-Übersicht ───────────────────────────────────────────
// Stand: siehe COUNTRY_DATA_ASOF. Bußgeldrahmen ist EU-weit durch
// Art. 34 NIS2-Richtlinie vorgegeben (Mindeststandard) — daher für
// alle Länder identisch. Behörden-/Gesetzesnamen bleiben in
// Originalsprache (Eigennamen werden nicht übersetzt).
const EU_PENALTY_BASELINE = {
  essential: 'bis zu 10 Mio. € oder 2 % des weltweiten Jahresumsatzes (der höhere Betrag)',
  important: 'bis zu 7 Mio. € oder 1,4 % des weltweiten Jahresumsatzes (der höhere Betrag)',
};

const COUNTRY_DATA = {
  DE: { flag: '🇩🇪', name: { de: 'Deutschland', en: 'Germany', fr: 'Allemagne', nl: 'Duitsland' }, authority: 'Bundesamt für Sicherheit in der Informationstechnik (BSI)', legislation: 'NIS2-Umsetzungs- und Cybersicherheitsstärkungsgesetz (NIS2UmsuCG)', status: 'adopted', statusNote: { de: 'National umgesetzt', en: 'Transposed into national law', fr: 'Transposé en droit national', nl: 'Omgezet in nationale wetgeving' }, csirt: 'CERT-Bund', notes: { de: 'Bestehende KRITIS-Regulierung wird integriert; BSI-IT-Grundschutz als anerkannte Baseline.', en: 'Existing KRITIS regulation is integrated; BSI IT-Grundschutz recognized as baseline.', fr: 'La réglementation KRITIS existante est intégrée ; BSI IT-Grundschutz reconnu comme référence.', nl: 'Bestaande KRITIS-regelgeving wordt geïntegreerd; BSI IT-Grundschutz erkend als baseline.' } },
  FR: { flag: '🇫🇷', name: { de: 'Frankreich', en: 'France', fr: 'France', nl: 'Frankrijk' }, authority: 'Agence nationale de la sécurité des systèmes d\'information (ANSSI)', legislation: 'Umsetzungsgesetz in parlamentarischer Beratung', status: 'draft', statusNote: { de: 'Gesetzentwurf, noch nicht verabschiedet', en: 'Draft law, not yet adopted', fr: 'Projet de loi, pas encore adopté', nl: 'Wetsontwerp, nog niet aangenomen' }, csirt: 'CERT-FR', notes: { de: 'Baut auf bestehendem OSE/LPM-Rahmenwerk auf.', en: 'Builds on the existing OSE/LPM framework.', fr: 'S\'appuie sur le cadre OSE/LPM existant.', nl: 'Bouwt voort op het bestaande OSE/LPM-kader.' } },
  NL: { flag: '🇳🇱', name: { de: 'Niederlande', en: 'Netherlands', fr: 'Pays-Bas', nl: 'Nederland' }, authority: 'NCSC-NL (wesentliche Einrichtungen) / RDI (wichtige Einrichtungen)', legislation: 'Cyberbeveiligingswet (Cbw)', status: 'adopted', statusNote: { de: 'In Kraft seit 15.08.2026', en: 'In force since 15 Aug 2026', fr: 'En vigueur depuis le 15/08/2026', nl: 'Van kracht sinds 15-08-2026' }, csirt: 'NCSC-NL', notes: { de: 'Duale Zuständigkeit je nach Einrichtungstyp.', en: 'Dual competence depending on entity type.', fr: 'Compétence duale selon le type d\'entité.', nl: 'Duale bevoegdheid afhankelijk van type entiteit.' } },
  BE: { flag: '🇧🇪', name: { de: 'Belgien', en: 'Belgium', fr: 'Belgique', nl: 'België' }, authority: 'Centre for Cybersecurity Belgium (CCB)', legislation: 'NIS2-Umsetzungsgesetz', status: 'adopted', statusNote: { de: 'National umgesetzt (früher Umsetzer)', en: 'Transposed (early adopter)', fr: 'Transposé (adoption précoce)', nl: 'Omgezet (vroege omzetter)' }, csirt: 'CERT.be', notes: { de: 'Eines der ersten Länder mit vollständiger Umsetzung.', en: 'One of the first countries with full transposition.', fr: 'Un des premiers pays avec une transposition complète.', nl: 'Een van de eerste landen met volledige omzetting.' } },
  IT: { flag: '🇮🇹', name: { de: 'Italien', en: 'Italy', fr: 'Italie', nl: 'Italië' }, authority: 'Agenzia per la Cybersicurezza Nazionale (ACN)', legislation: 'Decreto legislativo NIS2', status: 'adopted', statusNote: { de: 'National umgesetzt (früher Umsetzer)', en: 'Transposed (early adopter)', fr: 'Transposé (adoption précoce)', nl: 'Omgezet (vroege omzetter)' }, csirt: 'CSIRT Italia', notes: { de: 'Gestaffeltes Registrierungsverfahren nach Sektor.', en: 'Staggered registration procedure by sector.', fr: 'Procédure d\'enregistrement échelonnée par secteur.', nl: 'Gefaseerde registratieprocedure per sector.' } },
  ES: { flag: '🇪🇸', name: { de: 'Spanien', en: 'Spain', fr: 'Espagne', nl: 'Spanje' }, authority: 'Instituto Nacional de Ciberseguridad (INCIBE) / CCN', legislation: 'Umsetzungsgesetz noch nicht final verabschiedet', status: 'no-law', statusNote: { de: 'Noch kein verabschiedetes Umsetzungsgesetz', en: 'No transposition law adopted yet', fr: 'Aucune loi de transposition adoptée', nl: 'Nog geen omzettingswet aangenomen' }, csirt: 'INCIBE-CERT', notes: { de: 'Gehört zu den Mitgliedsstaaten ohne finales Gesetz (Stand Redaktionsschluss).', en: 'Among the member states without a final law (as of writing).', fr: 'Parmi les États membres sans loi finale (à la date de rédaction).', nl: 'Behoort tot de lidstaten zonder definitieve wet (bij redactiesluiting).' } },
  PL: { flag: '🇵🇱', name: { de: 'Polen', en: 'Poland', fr: 'Pologne', nl: 'Polen' }, authority: 'Ministerstwo Cyfryzacji / CSIRT NASK, GOV, MON', legislation: 'Novelle des Gesetzes über das nationale Cybersicherheitssystem (KSC)', status: 'draft', statusNote: { de: 'Gesetzentwurf in Beratung', en: 'Draft law under discussion', fr: 'Projet de loi en discussion', nl: 'Wetsontwerp in behandeling' }, csirt: 'CSIRT NASK', notes: { de: 'Drei-CSIRT-Modell (NASK, GOV, MON) bleibt bestehen.', en: 'Three-CSIRT model (NASK, GOV, MON) remains in place.', fr: 'Le modèle à trois CSIRT (NASK, GOV, MON) est maintenu.', nl: 'Drie-CSIRT-model (NASK, GOV, MON) blijft bestaan.' } },
  SE: { flag: '🇸🇪', name: { de: 'Schweden', en: 'Sweden', fr: 'Suède', nl: 'Zweden' }, authority: 'Myndigheten för samhällsskydd och beredskap (MSB)', legislation: 'Cybersäkerhetslag', status: 'progressing', statusNote: { de: 'Verabschiedeter Gesetzesrahmen, Feinausgestaltung läuft', en: 'Framework law adopted, detailed rules in progress', fr: 'Cadre législatif adopté, détails en cours d\'élaboration', nl: 'Kaderwet aangenomen, uitwerking loopt' }, csirt: 'CERT-SE', notes: { de: 'Sektorbehörden ergänzen MSB als zentrale Stelle.', en: 'Sector authorities complement MSB as the central body.', fr: 'Les autorités sectorielles complètent le MSB comme organe central.', nl: 'Sectorautoriteiten vullen MSB aan als centraal orgaan.' } },
  DK: { flag: '🇩🇰', name: { de: 'Dänemark', en: 'Denmark', fr: 'Danemark', nl: 'Denemarken' }, authority: 'Center for Cybersikkerhed (CFCS)', legislation: 'NIS2-Umsetzungsgesetz', status: 'progressing', statusNote: { de: 'Verabschiedeter Rahmen, Ausführungsbestimmungen in Arbeit', en: 'Framework adopted, implementing rules in progress', fr: 'Cadre adopté, règles d\'application en cours', nl: 'Kader aangenomen, uitvoeringsregels in bewerking' }, csirt: 'DK-CERT', notes: { de: 'Sektorspezifische Aufsicht ergänzend zu CFCS.', en: 'Sector-specific oversight in addition to CFCS.', fr: 'Surveillance sectorielle en complément du CFCS.', nl: 'Sectorspecifiek toezicht aanvullend op CFCS.' } },
  AT: { flag: '🇦🇹', name: { de: 'Österreich', en: 'Austria', fr: 'Autriche', nl: 'Oostenrijk' }, authority: 'Bundesamt für Cybersicherheit (im Aufbau) / BMI', legislation: 'NIS-2-Umsetzungsgesetz (NISG 2024)', status: 'in-force-soon', statusNote: { de: 'Verabschiedet, Hauptpflichten ab 01.10.2026', en: 'Adopted, main obligations from 1 Oct 2026', fr: 'Adoptée, obligations principales à partir du 01/10/2026', nl: 'Aangenomen, hoofdverplichtingen vanaf 01-10-2026' }, csirt: 'CERT.at', notes: { de: 'Übergangsfrist bis zum vollständigen Wirksamwerden der Pflichten.', en: 'Transition period until obligations take full effect.', fr: 'Période de transition jusqu\'à la pleine entrée en vigueur des obligations.', nl: 'Overgangsperiode tot de verplichtingen volledig van kracht worden.' } },
  IE: { flag: '🇮🇪', name: { de: 'Irland', en: 'Ireland', fr: 'Irlande', nl: 'Ierland' }, authority: 'National Cyber Security Centre (NCSC-IE)', legislation: 'Noch kein verabschiedetes Umsetzungsgesetz', status: 'no-law', statusNote: { de: 'Frühe Phase der Gesetzgebung', en: 'Early legislative stage', fr: 'Phase législative précoce', nl: 'Vroege wetgevingsfase' }, csirt: 'NCSC-IE', notes: { de: 'Gehört zu den Mitgliedsstaaten ohne finales Gesetz (Stand Redaktionsschluss).', en: 'Among the member states without a final law (as of writing).', fr: 'Parmi les États membres sans loi finale (à la date de rédaction).', nl: 'Behoort tot de lidstaten zonder definitieve wet (bij redactiesluiting).' } },
  CZ: { flag: '🇨🇿', name: { de: 'Tschechien', en: 'Czechia', fr: 'Tchéquie', nl: 'Tsjechië' }, authority: 'Národní úřad pro kybernetickou a informační bezpečnost (NÚKIB)', legislation: 'Zákon o kybernetické bezpečnosti (novelisiert)', status: 'adopted', statusNote: { de: 'National umgesetzt', en: 'Transposed into national law', fr: 'Transposé en droit national', nl: 'Omgezet in nationale wetgeving' }, csirt: 'GovCERT.CZ', notes: { de: 'NÚKIB als zentrale Aufsichts- und Zertifizierungsstelle.', en: 'NÚKIB as the central oversight and certification body.', fr: 'NÚKIB comme organe central de surveillance et de certification.', nl: 'NÚKIB als centraal toezichts- en certificeringsorgaan.' } },
  PT: { flag: '🇵🇹', name: { de: 'Portugal', en: 'Portugal', fr: 'Portugal', nl: 'Portugal' }, authority: 'Centro Nacional de Cibersegurança (CNCS)', legislation: 'Umsetzungsgesetz', status: 'progressing', statusNote: { de: 'Verabschiedeter Rahmen, Feinausgestaltung läuft', en: 'Framework adopted, detailed rules in progress', fr: 'Cadre adopté, détails en cours d\'élaboration', nl: 'Kader aangenomen, uitwerking loopt' }, csirt: 'CERT.PT', notes: { de: '', en: '', fr: '', nl: '' } },
  FI: { flag: '🇫🇮', name: { de: 'Finnland', en: 'Finland', fr: 'Finlande', nl: 'Finland' }, authority: 'Traficom / Kyberturvallisuuskeskus (NCSC-FI)', legislation: 'Umsetzungsgesetz', status: 'progressing', statusNote: { de: 'Verabschiedeter Rahmen, Feinausgestaltung läuft', en: 'Framework adopted, detailed rules in progress', fr: 'Cadre adopté, détails en cours d\'élaboration', nl: 'Kader aangenomen, uitwerking loopt' }, csirt: 'NCSC-FI', notes: { de: '', en: '', fr: '', nl: '' } },
  GR: { flag: '🇬🇷', name: { de: 'Griechenland', en: 'Greece', fr: 'Grèce', nl: 'Griekenland' }, authority: 'National Cybersecurity Authority (NCA)', legislation: 'Umsetzungsgesetz', status: 'adopted', statusNote: { de: 'National umgesetzt', en: 'Transposed into national law', fr: 'Transposé en droit national', nl: 'Omgezet in nationale wetgeving' }, csirt: 'CERT-EL', notes: { de: '', en: '', fr: '', nl: '' } },
};

const STATUS_LABELS = {
  'adopted':       { color: '#16a34a', label: { de: 'Umgesetzt', en: 'Transposed', fr: 'Transposé', nl: 'Omgezet' } },
  'in-force-soon': { color: '#65a30d', label: { de: 'Verabschiedet, tritt in Kraft', en: 'Adopted, entering into force', fr: 'Adoptée, en entrée en vigueur', nl: 'Aangenomen, treedt in werking' } },
  'progressing':   { color: '#ca8a04', label: { de: 'Rahmen verabschiedet, Details in Arbeit', en: 'Framework adopted, details in progress', fr: 'Cadre adopté, détails en cours', nl: 'Kader aangenomen, details in bewerking' } },
  'draft':         { color: '#ea580c', label: { de: 'Gesetzentwurf', en: 'Draft law', fr: 'Projet de loi', nl: 'Wetsontwerp' } },
  'no-law':        { color: '#dc2626', label: { de: 'Kein Gesetz verabschiedet', en: 'No law adopted', fr: 'Aucune loi adoptée', nl: 'Geen wet aangenomen' } },
};

// ─── Klassifizierungs-Labels ─────────────────────────────────────
const CLASSIFICATION_LABELS = {
  'essential': { color: '#dc2626', label: { de: 'Wesentliche Einrichtung (Essential Entity)', en: 'Essential Entity', fr: 'Entité essentielle', nl: 'Essentiële entiteit' }, desc: { de: 'Unterliegt der strengeren Aufsicht (proaktive Prüfungen möglich).', en: 'Subject to stricter supervision (proactive audits possible).', fr: 'Soumise à une surveillance plus stricte (audits proactifs possibles).', nl: 'Onderworpen aan strenger toezicht (proactieve controles mogelijk).' } },
  'important': { color: '#ea580c', label: { de: 'Wichtige Einrichtung (Important Entity)', en: 'Important Entity', fr: 'Entité importante', nl: 'Belangrijke entiteit' }, desc: { de: 'Unterliegt reaktiver Aufsicht (Prüfung im Anlassfall).', en: 'Subject to reactive supervision (ex-post audits).', fr: 'Soumise à une surveillance réactive (contrôles a posteriori).', nl: 'Onderworpen aan reactief toezicht (controle achteraf).' } },
  'out-of-scope-likely': { color: '#6b7280', label: { de: 'Voraussichtlich nicht im Anwendungsbereich', en: 'Likely out of scope', fr: 'Probablement hors champ d\'application', nl: 'Waarschijnlijk buiten toepassingsgebied' }, desc: { de: 'Nach den angegebenen Schwellenwerten vermutlich nicht NIS2-pflichtig — Einzelfallprüfung empfohlen.', en: 'Based on the given thresholds, likely not subject to NIS2 — individual assessment recommended.', fr: 'Selon les seuils indiqués, probablement non soumise à NIS2 — évaluation individuelle recommandée.', nl: 'Op basis van de opgegeven drempels waarschijnlijk niet NIS2-plichtig — individuele beoordeling aanbevolen.' } },
};
