/* © 2026 Claude Hecker — NIS2 Quick-Check — AGPL-3.0
   ================================================================
   Internationalisierung — alle 24 EU-Amtssprachen vollständig befüllt.
   ================================================================ */

const LANGUAGES = [
  { code: 'bg', name: 'Bulgarian', native: 'Български', flag: '🇧🇬' },
  { code: 'hr', name: 'Croatian', native: 'Hrvatski', flag: '🇭🇷' },
  { code: 'cs', name: 'Czech', native: 'Čeština', flag: '🇨🇿' },
  { code: 'da', name: 'Danish', native: 'Dansk', flag: '🇩🇰' },
  { code: 'nl', name: 'Dutch', native: 'Nederlands', flag: '🇳🇱' },
  { code: 'en', name: 'English', native: 'English', flag: '🇬🇧' },
  { code: 'et', name: 'Estonian', native: 'Eesti', flag: '🇪🇪' },
  { code: 'fi', name: 'Finnish', native: 'Suomi', flag: '🇫🇮' },
  { code: 'fr', name: 'French', native: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'German', native: 'Deutsch', flag: '🇩🇪' },
  { code: 'el', name: 'Greek', native: 'Ελληνικά', flag: '🇬🇷' },
  { code: 'hu', name: 'Hungarian', native: 'Magyar', flag: '🇭🇺' },
  { code: 'ga', name: 'Irish', native: 'Gaeilge', flag: '🇮🇪' },
  { code: 'it', name: 'Italian', native: 'Italiano', flag: '🇮🇹' },
  { code: 'lv', name: 'Latvian', native: 'Latviešu', flag: '🇱🇻' },
  { code: 'lt', name: 'Lithuanian', native: 'Lietuvių', flag: '🇱🇹' },
  { code: 'mt', name: 'Maltese', native: 'Malti', flag: '🇲🇹' },
  { code: 'pl', name: 'Polish', native: 'Polski', flag: '🇵🇱' },
  { code: 'pt', name: 'Portuguese', native: 'Português', flag: '🇵🇹' },
  { code: 'ro', name: 'Romanian', native: 'Română', flag: '🇷🇴' },
  { code: 'sk', name: 'Slovak', native: 'Slovenčina', flag: '🇸🇰' },
  { code: 'sl', name: 'Slovenian', native: 'Slovenščina', flag: '🇸🇮' },
  { code: 'es', name: 'Spanish', native: 'Español', flag: '🇪🇸' },
  { code: 'sv', name: 'Swedish', native: 'Svenska', flag: '🇸🇪' },
];

const FULLY_TRANSLATED = LANGUAGES.map(l => l.code);

// ─── UI-Strings (alle 24 Sprachen) ───────────────────────────────
const UI = {
  title: { bg:'NIS2 Quick-Check', hr:'NIS2 Quick-Check', cs:'NIS2 Quick-Check', da:'NIS2 Quick-Check', nl:'NIS2 Quick-Check', en:'NIS2 Quick-Check', et:'NIS2 Quick-Check', fi:'NIS2 Quick-Check', fr:'NIS2 Quick-Check', de:'NIS2 Quick-Check', el:'NIS2 Quick-Check', hu:'NIS2 Quick-Check', ga:'NIS2 Quick-Check', it:'NIS2 Quick-Check', lv:'NIS2 Quick-Check', lt:'NIS2 Quick-Check', mt:'NIS2 Quick-Check', pl:'NIS2 Quick-Check', pt:'NIS2 Quick-Check', ro:'NIS2 Quick-Check', sk:'NIS2 Quick-Check', sl:'NIS2 Quick-Check', es:'NIS2 Quick-Check', sv:'NIS2 Quick-Check' },

  lead: {
    bg:'Безплатна, изцяло локална самопроверка за приблизителна оценка на степента на съответствие с десетте области на мерки по чл. 21(2) от Директива NIS2.',
    hr:'Besplatna, u potpunosti lokalna samoprovjera za grubu procjenu stanja provedbe u odnosu na deset područja mjera iz čl. 21(2) Direktive NIS2.',
    cs:'Bezplatná, zcela lokální sebehodnoticí kontrola pro hrubý odhad stavu implementace vůči deseti oblastem opatření podle čl. 21(2) směrnice NIS2.',
    da:'Et gratis, fuldt lokalt selvtjek til en grov vurdering af din implementeringsstatus i forhold til de ti foranstaltningsområder i artikel 21(2) i NIS2-direktivet.',
    nl:'Een gratis, volledig lokaal draaiende zelfcheck om je implementatiestatus grofweg in te schatten ten opzichte van de tien maatregelgebieden uit art. 21(2) van de NIS2-richtlijn.',
    en:'A free, fully local self-check to get a rough estimate of your implementation status against the ten measure areas in Article 21(2) of the NIS2 Directive.',
    et:'Tasuta, täielikult kohalik enesekontroll, et saada ligikaudne hinnang oma rakendamise seisu kohta NIS2 direktiivi artikli 21(2) kümne meetmevaldkonna suhtes.',
    fi:'Maksuton, täysin paikallisesti toimiva itsearviointi, jolla saat karkean arvion toteutustilastasi NIS2-direktiivin 21(2) artiklan kymmenen toimenpidealueen suhteen.',
    fr:'Une auto-évaluation gratuite et entièrement locale pour estimer approximativement votre niveau de mise en œuvre au regard des dix domaines de mesures de l\'article 21(2) de la directive NIS2.',
    de:'Ein kostenloser, rein lokal laufender Selbst-Check zur groben Einschätzung des eigenen Umsetzungsstands gegenüber den zehn Maßnahmenbereichen aus Art. 21(2) der NIS2-Richtlinie.',
    el:'Ένας δωρεάν, εξ ολοκλήρου τοπικός αυτοέλεγχος για μια χονδρική εκτίμηση του βαθμού εφαρμογής σε σχέση με τους δέκα τομείς μέτρων του άρθρου 21(2) της Οδηγίας NIS2.',
    hu:'Ingyenes, teljesen helyben futó önellenőrzés a NIS2 irányelv 21(2) cikkében szereplő tíz intézkedési terület megvalósítási állapotának hozzávetőleges felmérésére.',
    ga:'Féinseiceáil saor in aisce, atá go hiomlán áitiúil, chun meastachán garbh a fháil ar do stádas feidhmithe i gcoinne na ndeich réimse beart in Airteagal 21(2) den Treoir NIS2.',
    it:'Un\'autovalutazione gratuita ed interamente locale per stimare approssimativamente il proprio livello di attuazione rispetto ai dieci ambiti di misure dell\'art. 21(2) della direttiva NIS2.',
    lv:'Bezmaksas, pilnībā lokāla pašpārbaude, lai aptuveni novērtētu ieviešanas statusu attiecībā uz desmit pasākumu jomām NIS2 direktīvas 21.(2). pantā.',
    lt:'Nemokamas, visiškai vietinis savipatikros įrankis, skirtas apytiksliai įvertinti įgyvendinimo būklę pagal dešimt NIS2 direktyvos 21(2) straipsnio priemonių sričių.',
    mt:'Verifika bla ħlas, kompletament lokali, biex tikseb stima approssimattiva tal-istatus tal-implimentazzjoni tiegħek fir-rigward tal-għaxar oqsma ta\' miżuri fl-Artikolu 21(2) tad-Direttiva NIS2.',
    pl:'Bezpłatne, w pełni lokalne samobadanie umożliwiające przybliżoną ocenę stanu wdrożenia w odniesieniu do dziesięciu obszarów środków z art. 21(2) dyrektywy NIS2.',
    pt:'Uma autoavaliação gratuita e totalmente local para obter uma estimativa aproximada do seu estado de implementação relativamente às dez áreas de medidas do artigo 21.º(2) da Diretiva NIS2.',
    ro:'O autoevaluare gratuită, complet locală, pentru o estimare aproximativă a stadiului de implementare față de cele zece domenii de măsuri din art. 21(2) al Directivei NIS2.',
    sk:'Bezplatná, plne lokálna sebahodnotiaca kontrola na hrubý odhad stavu implementácie voči desiatim oblastiam opatrení podľa čl. 21(2) smernice NIS2.',
    sl:'Brezplačen, popolnoma lokalen samopregled za grobo oceno stanja izvajanja glede na deset področij ukrepov iz člena 21(2) Direktive NIS2.',
    es:'Una autoevaluación gratuita y totalmente local para obtener una estimación aproximada de su nivel de implementación respecto a las diez áreas de medidas del art. 21(2) de la Directiva NIS2.',
    sv:'Ett kostnadsfritt, helt lokalt självtest för en grov uppskattning av din implementeringsstatus mot de tio åtgärdsområdena i artikel 21(2) i NIS2-direktivet.',
  },
  disclaimer: { bg:'Не замества правна консултация.', hr:'Ne zamjenjuje pravni savjet.', cs:'Nenahrazuje právní poradenství.', da:'Ikke en erstatning for juridisk rådgivning.', nl:'Geen vervanging voor juridisch advies.', en:'Not a substitute for legal advice.', et:'Ei asenda õigusnõustamist.', fi:'Ei korvaa oikeudellista neuvontaa.', fr:'Ne remplace pas un conseil juridique.', de:'Kein Ersatz für Rechtsberatung.', el:'Δεν υποκαθιστά τη νομική συμβουλή.', hu:'Nem helyettesíti a jogi tanácsadást.', ga:'Ní ionadaí é seo do chomhairle dhlíthiúil.', it:'Non sostituisce una consulenza legale.', lv:'Neaizstāj juridisko konsultāciju.', lt:'Nepakeičia teisinės konsultacijos.', mt:'Mhux sostitut għal parir legali.', pl:'Nie zastępuje porady prawnej.', pt:'Não substitui aconselhamento jurídico.', ro:'Nu înlocuiește consultanța juridică.', sk:'Nenahrádza právne poradenstvo.', sl:'Ne nadomešča pravnega nasveta.', es:'No sustituye el asesoramiento jurídico.', sv:'Ersätter inte juridisk rådgivning.' },
  disclaimerBody: {
    bg:'Този инструмент предоставя само необвързваща ориентация. Задължителната класификация и задълженията за прилагане зависят от съответното национално транспониране — моля, потвърдете с компетентния орган или квалифициран юрист.',
    hr:'Ovaj alat pruža samo neobvezujuću orijentaciju. Obvezujuća klasifikacija i obveze provedbe ovise o odgovarajućoj nacionalnoj transpoziciji — potvrdite kod nadležnog tijela ili kvalificiranog pravnog savjetnika.',
    cs:'Tento nástroj poskytuje pouze nezávaznou orientaci. Závazná klasifikace a povinnosti implementace závisí na příslušné vnitrostátní transpozici — ověřte prosím u příslušného orgánu nebo kvalifikovaného právního poradce.',
    da:'Dette værktøj giver kun ikke-bindende orientering. Bindende klassificering og implementeringsforpligtelser afhænger af den respektive nationale gennemførelse — bekræft venligst hos den kompetente myndighed eller kvalificeret juridisk rådgivning.',
    nl:'Deze tool biedt alleen een vrijblijvende oriëntatie. Bindende classificatie en implementatieverplichtingen hangen af van de nationale omzetting — overleg met de bevoegde autoriteit of gekwalificeerd juridisch advies.',
    en:'This tool provides non-binding orientation only. Binding classification and implementation obligations depend on the respective national transposition — please confirm with the competent authority or qualified legal counsel.',
    et:'See tööriist pakub ainult mittesiduvat suunist. Siduv klassifikatsioon ja rakenduskohustused sõltuvad vastavast riiklikust ülevõtmisest — palun kinnitage pädeva asutuse või kvalifitseeritud õigusnõustajaga.',
    fi:'Tämä työkalu tarjoaa vain sitomatonta suuntaa-antavaa tietoa. Sitova luokittelu ja toteutusvelvoitteet riippuvat kansallisesta täytäntöönpanosta — vahvista asia toimivaltaiselta viranomaiselta tai pätevältä lakimieheltä.',
    fr:'Cet outil fournit uniquement une orientation non contraignante. La classification et les obligations de mise en œuvre contraignantes dépendent de la transposition nationale respective — merci de vérifier auprès de l\'autorité compétente ou d\'un conseil juridique qualifié.',
    de:'Dieses Tool liefert eine unverbindliche Orientierung. Verbindliche Einstufung und Umsetzungspflichten hängen von der jeweiligen nationalen Umsetzung ab — bitte mit der zuständigen Behörde bzw. einer fachkundigen Beratung abstimmen.',
    el:'Αυτό το εργαλείο παρέχει μόνο μη δεσμευτικό προσανατολισμό. Η δεσμευτική ταξινόμηση και οι υποχρεώσεις εφαρμογής εξαρτώνται από την αντίστοιχη εθνική μεταφορά — παρακαλούμε επιβεβαιώστε με την αρμόδια αρχή ή εξειδικευμένο νομικό σύμβουλο.',
    hu:'Ez az eszköz kizárólag nem kötelező érvényű tájékoztatást nyújt. A kötelező besorolás és a végrehajtási kötelezettségek a megfelelő nemzeti átültetéstől függenek — kérjük, egyeztessen az illetékes hatósággal vagy szakképzett jogi tanácsadóval.',
    ga:'Ní sholáthraíonn an uirlis seo ach treoshuíomh neamhcheangailteach. Braitheann an aicmiú ceangailteach agus na hoibleagáidí cur chun feidhme ar an trasuí náisiúnta ábhartha — deimhnigh le do thoil leis an údarás inniúil nó le comhairleoir dlí cáilithe.',
    it:'Questo strumento fornisce solo un orientamento non vincolante. La classificazione vincolante e gli obblighi di attuazione dipendono dal rispettivo recepimento nazionale — si prega di verificare con l\'autorità competente o un consulente legale qualificato.',
    lv:'Šis rīks sniedz tikai nesaistošu orientāciju. Saistošā klasifikācija un ieviešanas pienākumi ir atkarīgi no attiecīgās valsts transponēšanas — lūdzu, apstipriniet ar kompetento iestādi vai kvalificētu juridisko konsultantu.',
    lt:'Šis įrankis pateikia tik neįpareigojančią orientaciją. Privaloma klasifikacija ir įgyvendinimo įsipareigojimai priklauso nuo atitinkamo nacionalinio perkėlimo — patvirtinkite su kompetentinga institucija ar kvalifikuotu teisės konsultantu.',
    mt:'Din l-għodda tipprovdi biss orjentazzjoni mhux vinkolanti. Il-klassifikazzjoni vinkolanti u l-obbligi ta\' implimentazzjoni jiddependu mit-traspożizzjoni nazzjonali rispettiva — jekk jogħġbok ikkonferma mal-awtorità kompetenti jew konsulent legali kwalifikat.',
    pl:'To narzędzie zapewnia jedynie niewiążącą orientację. Wiążąca klasyfikacja i obowiązki wdrożeniowe zależą od odpowiedniej transpozycji krajowej — proszę potwierdzić z właściwym organem lub wykwalifikowanym doradcą prawnym.',
    pt:'Esta ferramenta fornece apenas orientação não vinculativa. A classificação vinculativa e as obrigações de implementação dependem da respetiva transposição nacional — confirme com a autoridade competente ou consultoria jurídica qualificada.',
    ro:'Acest instrument oferă doar o orientare neobligatorie. Clasificarea obligatorie și obligațiile de implementare depind de transpunerea națională respectivă — vă rugăm să confirmați cu autoritatea competentă sau un consilier juridic calificat.',
    sk:'Tento nástroj poskytuje iba nezáväznú orientáciu. Záväzná klasifikácia a implementačné povinnosti závisia od príslušnej vnútroštátnej transpozície — potvrďte, prosím, u príslušného orgánu alebo kvalifikovaného právneho poradcu.',
    sl:'To orodje zagotavlja le nezavezujočo usmeritev. Zavezujoča razvrstitev in obveznosti izvajanja so odvisne od ustreznega nacionalnega prenosa — prosimo, preverite pri pristojnem organu ali usposobljenem pravnem svetovalcu.',
    es:'Esta herramienta ofrece únicamente una orientación no vinculante. La clasificación vinculante y las obligaciones de implementación dependen de la respectiva transposición nacional — confirme con la autoridad competente o asesoría legal cualificada.',
    sv:'Detta verktyg ger endast icke-bindande vägledning. Bindande klassificering och genomförandeskyldigheter beror på respektive nationellt genomförande — bekräfta med den behöriga myndigheten eller kvalificerad juridisk rådgivning.',
  },
  countryDataAsOf: { bg:'Данни за държавата към', hr:'Podaci o zemlji na dan', cs:'Údaje o zemi k', da:'Landedata pr.', nl:'Landgegevens per', en:'Country data as of', et:'Riigi andmed seisuga', fi:'Maatiedot päivätty', fr:'Données pays au', de:'Länderdaten Stand', el:'Στοιχεία χώρας από', hu:'Országadatok állapota', ga:'Sonraí tíre amhail an', it:'Dati sul paese aggiornati al', lv:'Valsts dati uz', lt:'Šalies duomenys nuo', mt:'Data tal-pajjiż mid-data', pl:'Dane kraju na dzień', pt:'Dados do país em', ro:'Date despre țară valabile la', sk:'Údaje o krajine k', sl:'Podatki o državi na dan', es:'Datos del país a fecha de', sv:'Landdata per' },
  featStructure: { bg:'10 области × 5 въпроса (общо 50 въпроса), скала на зрялост 0–4', hr:'10 domena × 5 pitanja (ukupno 50 pitanja), ljestvica zrelosti 0–4', cs:'10 domén × 5 otázek (celkem 50 otázek), škála zralosti 0–4', da:'10 domæner × 5 spørgsmål (50 spørgsmål i alt), modenhedsskala 0–4', nl:'10 domeinen × 5 vragen (50 vragen totaal), volwassenheidsschaal 0–4', en:'10 domains × 5 questions (50 questions total), maturity scale 0–4', et:'10 valdkonda × 5 küsimust (kokku 50 küsimust), küpsusskaala 0–4', fi:'10 osa-aluetta × 5 kysymystä (yhteensä 50 kysymystä), kypsyysasteikko 0–4', fr:'10 domaines × 5 questions (50 questions au total), échelle de maturité 0–4', de:'10 Domänen × 5 Fragen (50 Fragen gesamt), Reifegrad-Skala 0–4', el:'10 τομείς × 5 ερωτήσεις (50 ερωτήσεις συνολικά), κλίμακα ωριμότητας 0–4', hu:'10 terület × 5 kérdés (összesen 50 kérdés), érettségi skála 0–4', ga:'10 réimse × 5 cheist (50 ceist san iomlán), scála aibíochta 0–4', it:'10 domini × 5 domande (50 domande totali), scala di maturità 0–4', lv:'10 jomas × 5 jautājumi (kopā 50 jautājumi), brieduma skala 0–4', lt:'10 sričių × 5 klausimai (iš viso 50 klausimų), brandos skalė 0–4', mt:'10 oqsma × 5 mistoqsijiet (50 mistoqsija b\'kollox), skala tal-maturità 0–4', pl:'10 domen × 5 pytań (50 pytań łącznie), skala dojrzałości 0–4', pt:'10 domínios × 5 perguntas (50 perguntas no total), escala de maturidade 0–4', ro:'10 domenii × 5 întrebări (50 de întrebări în total), scară de maturitate 0–4', sk:'10 domén × 5 otázok (spolu 50 otázok), škála zrelosti 0–4', sl:'10 domen × 5 vprašanj (skupaj 50 vprašanj), lestvica zrelosti 0–4', es:'10 dominios × 5 preguntas (50 preguntas en total), escala de madurez 0–4', sv:'10 domäner × 5 frågor (50 frågor totalt), mognadsskala 0–4' },
  featClassify: { bg:'Автоматично приблизително класифициране Съществен/Важен по сектор + размер', hr:'Automatska gruba klasifikacija Ključni/Važni prema sektoru + veličini', cs:'Automatická hrubá klasifikace Zásadní/Důležitý podle odvětví + velikosti', da:'Automatisk grov klassificering Væsentlig/Vigtig efter sektor + størrelse', nl:'Automatische grove classificatie Essentieel/Belangrijk op basis van sector + omvang', en:'Automatic rough classification Essential/Important by sector + size', et:'Automaatne ligikaudne klassifikatsioon oluline/tähtis sektori + suuruse järgi', fi:'Automaattinen karkea luokittelu keskeinen/tärkeä toimialan + koon mukaan', fr:'Classification approximative automatique Essentiel/Important selon secteur + taille', de:'Automatische grobe Einstufung Essential/Important nach Sektor + Größe', el:'Αυτόματη χονδρική ταξινόμηση Βασική/Σημαντική βάσει τομέα + μεγέθους', hu:'Automatikus hozzávetőleges besorolás alapvető/fontos ágazat + méret alapján', ga:'Aicmiú garbh uathoibríoch Riachtanach/Tábhachtach de réir earnála + méide', it:'Classificazione approssimativa automatica Essenziale/Importante per settore + dimensione', lv:'Automātiska aptuvena klasifikācija būtisks/svarīgs pēc nozares + lieluma', lt:'Automatinis apytikslis klasifikavimas esminis/svarbus pagal sektorių + dydį', mt:'Klassifikazzjoni approssimattiva awtomatika Essenzjali/Importanti skont is-settur + daqs', pl:'Automatyczna przybliżona klasyfikacja kluczowy/ważny wg sektora + wielkości', pt:'Classificação aproximada automática Essencial/Importante por setor + dimensão', ro:'Clasificare automată aproximativă esențial/important în funcție de sector + dimensiune', sk:'Automatická hrubá klasifikácia kľúčový/dôležitý podľa odvetvia + veľkosti', sl:'Samodejna groba razvrstitev bistveni/pomembni glede na sektor + velikost', es:'Clasificación aproximada automática Esencial/Importante según sector + tamaño', sv:'Automatisk grov klassificering väsentlig/viktig efter sektor + storlek' },
  featDashboard: { bg:'Табло с резултати с радарна и стълбовидна диаграма, анализ на пропуските', hr:'Nadzorna ploča rezultata s radarskim i stupčastim dijagramom, analiza nedostataka', cs:'Panel výsledků s paprskovým a sloupcovým grafem, analýza mezer', da:'Resultatdashboard med radar- og søjlediagram, gap-analyse', nl:'Resultatendashboard met radar- en staafdiagram, gap-analyse', en:'Result dashboard with radar and bar chart, gap analysis', et:'Tulemuste töölaud radar- ja tulpdiagrammiga, lõhede analüüs', fi:'Tulostaulu tutka- ja pylväskaaviolla, kuiluanalyysi', fr:'Tableau de bord des résultats avec diagramme radar et à barres, analyse des écarts', de:'Ergebnis-Dashboard mit Radar- und Balkendiagramm, Gap-Analyse', el:'Πίνακας αποτελεσμάτων με ραντάρ και ραβδόγραμμα, ανάλυση κενών', hu:'Eredménypanel radar- és oszlopdiagrammal, hiányelemzés', ga:'Painéal torthaí le léaráid radair agus barra, anailís bearna', it:'Cruscotto dei risultati con grafico radar e a barre, analisi dei divari', lv:'Rezultātu panelis ar radara un joslu diagrammu, atšķirību analīze', lt:'Rezultatų skydelis su radaro ir stulpelių diagrama, spragų analizė', mt:'Dashboard tar-riżultati b\'grafika radar u ta\' barra, analiżi tal-lakuni', pl:'Panel wyników z wykresem radarowym i słupkowym, analiza luk', pt:'Painel de resultados com gráfico radar e de barras, análise de lacunas', ro:'Tablou de bord al rezultatelor cu grafic radar și cu bare, analiza decalajelor', sk:'Panel výsledkov s radarovým a stĺpcovým grafom, analýza medzier', sl:'Nadzorna plošča rezultatov z radarskim in stolpčnim grafikonom, analiza vrzeli', es:'Panel de resultados con gráfico radar y de barras, análisis de brechas', sv:'Resultatpanel med radar- och stapeldiagram, gapanalys' },
  featCountries: { bg:'Информация за избраната държава: компетентен орган, закон, статус на транспониране (всичките 27 страни от ЕС)', hr:'Informacije o odabranoj zemlji: nadležno tijelo, zakon, status transpozicije (svih 27 zemalja EU)', cs:'Informace o vybrané zemi: příslušný orgán, zákon, stav transpozice (všech 27 zemí EU)', da:'Landeoplysninger for dit valgte land: kompetent myndighed, lov, gennemførelsesstatus (alle 27 EU-lande)', nl:'Landinformatie voor het gekozen land: bevoegde autoriteit, wet, omzettingsstatus (alle 27 EU-landen)', en:'Country information for your selected country: competent authority, law, transposition status (all 27 EU countries)', et:'Valitud riigi teave: pädev asutus, seadus, ülevõtmise staatus (kõik 27 ELi riiki)', fi:'Valitun maan tiedot: toimivaltainen viranomainen, laki, täytäntöönpanotilanne (kaikki 27 EU-maata)', fr:'Informations sur le pays sélectionné : autorité compétente, loi, état de transposition (27 pays UE)', de:'Länderinformation zum gewählten Land: zuständige Behörde, Gesetz, Umsetzungsstand (alle 27 EU-Länder)', el:'Πληροφορίες για την επιλεγμένη χώρα: αρμόδια αρχή, νόμος, κατάσταση μεταφοράς (και οι 27 χώρες της ΕΕ)', hu:'A kiválasztott ország adatai: illetékes hatóság, jogszabály, átültetési állapot (mind a 27 uniós ország)', ga:'Faisnéis faoin tír roghnaithe: údarás inniúil, dlí, stádas trasuite (gach ceann de na 27 tír san AE)', it:'Informazioni sul paese selezionato: autorità competente, legge, stato di recepimento (tutti i 27 paesi UE)', lv:'Informācija par izvēlēto valsti: kompetentā iestāde, likums, transponēšanas statuss (visas 27 ES valstis)', lt:'Pasirinktos šalies informacija: kompetentinga institucija, įstatymas, perkėlimo statusas (visos 27 ES šalys)', mt:'Informazzjoni dwar il-pajjiż magħżul: awtorità kompetenti, liġi, status ta\' traspożizzjoni (il-27 pajjiż tal-UE kollha)', pl:'Informacje o wybranym kraju: właściwy organ, ustawa, stan transpozycji (wszystkie 27 krajów UE)', pt:'Informações sobre o país selecionado: autoridade competente, lei, estado de transposição (todos os 27 países da UE)', ro:'Informații despre țara selectată: autoritate competentă, lege, stadiu de transpunere (toate cele 27 de țări UE)', sk:'Informácie o vybranej krajine: príslušný orgán, zákon, stav transpozície (všetkých 27 krajín EÚ)', sl:'Informacije o izbrani državi: pristojni organ, zakon, stanje prenosa (vseh 27 držav EU)', es:'Información sobre el país seleccionado: autoridad competente, ley, estado de transposición (los 27 países de la UE)', sv:'Landinformation för ditt valda land: behörig myndighet, lag, genomförandestatus (alla 27 EU-länder)' },
  featExport: { bg:'PDF експорт (изглед за печат), JSON експорт/импорт, автоматично запазване в браузъра', hr:'PDF izvoz (prikaz za ispis), JSON izvoz/uvoz, automatsko spremanje u pregledniku', cs:'Export do PDF (náhled tisku), export/import JSON, automatické ukládání v prohlížeči', da:'PDF-eksport (udskriftsvisning), JSON-eksport/import, automatisk gemning i browseren', nl:'PDF-export (afdrukweergave), JSON-export/import, automatisch opslaan in de browser', en:'PDF export (print view), JSON export/import, automatic browser autosave', et:'PDF-eksport (prindivaade), JSON-eksport/import, automaatne salvestamine brauseris', fi:'PDF-vienti (tulostusnäkymä), JSON-vienti/tuonti, automaattinen tallennus selaimeen', fr:'Export PDF (vue impression), export/import JSON, sauvegarde automatique dans le navigateur', de:'PDF-Export (Druckansicht), JSON-Export/Import, automatisches Zwischenspeichern im Browser', el:'Εξαγωγή PDF (προβολή εκτύπωσης), εξαγωγή/εισαγωγή JSON, αυτόματη αποθήκευση στο πρόγραμμα περιήγησης', hu:'PDF-exportálás (nyomtatási nézet), JSON-export/import, automatikus mentés a böngészőben', ga:'Easpórtáil PDF (amharc priontála), easpórtáil/iompórtáil JSON, uathshábháil bhrabhsálaí', it:'Esportazione PDF (vista stampa), esportazione/importazione JSON, salvataggio automatico nel browser', lv:'PDF eksports (drukas skats), JSON eksports/imports, automātiska saglabāšana pārlūkprogrammā', lt:'PDF eksportas (spausdinimo peržiūra), JSON eksportas/importas, automatinis išsaugojimas naršyklėje', mt:'Esportazzjoni PDF (dehra tal-istampar), esportazzjoni/importazzjoni JSON, salvataġġ awtomatiku fil-browser', pl:'Eksport PDF (widok wydruku), eksport/import JSON, automatyczny zapis w przeglądarce', pt:'Exportação PDF (vista de impressão), exportação/importação JSON, guardar automático no navegador', ro:'Export PDF (previzualizare tipărire), export/import JSON, salvare automată în browser', sk:'Export do PDF (náhľad tlače), export/import JSON, automatické ukladanie v prehliadači', sl:'Izvoz v PDF (predogled tiskanja), izvoz/uvoz JSON, samodejno shranjevanje v brskalniku', es:'Exportación a PDF (vista de impresión), exportación/importación JSON, autoguardado automático en el navegador', sv:'PDF-export (utskriftsvy), JSON-export/import, automatisk sparning i webbläsaren' },
  featLocal: { bg:'Работи изцяло локално — никакви данни не напускат браузъра', hr:'Radi u potpunosti lokalno — nikakvi podaci ne napuštaju preglednik', cs:'Funguje zcela lokálně — žádná data neopouštějí prohlížeč', da:'Kører helt lokalt — ingen data forlader browseren', nl:'Werkt volledig lokaal — er verlaten nooit gegevens de browser', en:'Runs entirely locally — no data ever leaves the browser', et:'Töötab täielikult kohapeal — andmed ei lahku kunagi brauserist', fi:'Toimii täysin paikallisesti — tiedot eivät koskaan poistu selaimesta', fr:'Fonctionne entièrement en local — aucune donnée ne quitte le navigateur', de:'Läuft komplett lokal — keine Daten verlassen den Browser', el:'Λειτουργεί εξ ολοκλήρου τοπικά — κανένα δεδομένο δεν φεύγει από το πρόγραμμα περιήγησης', hu:'Teljesen helyben fut — az adatok soha nem hagyják el a böngészőt', ga:'Ritheann sé go hiomlán go háitiúil — ní fhágann aon sonraí an brabhsálaí riamh', it:'Funziona interamente in locale — nessun dato lascia mai il browser', lv:'Darbojas pilnībā lokāli — dati nekad neatstāj pārlūkprogrammu', lt:'Veikia visiškai vietoje — duomenys niekada nepalieka naršyklės', mt:'Jaħdem kompletament lokalment — l-ebda data qatt ma titlaq mill-browser', pl:'Działa w pełni lokalnie — żadne dane nigdy nie opuszczają przeglądarki', pt:'Funciona totalmente localmente — os dados nunca saem do navegador', ro:'Funcționează complet local — datele nu părăsesc niciodată browserul', sk:'Funguje úplne lokálne — žiadne údaje neopúšťajú prehliadač', sl:'Deluje popolnoma lokalno — podatki nikoli ne zapustijo brskalnika', es:'Funciona completamente en local — los datos nunca salen del navegador', sv:'Körs helt lokalt — ingen data lämnar någonsin webbläsaren' },
  start: { bg:'Старт', hr:'Početak', cs:'Start', da:'Start', nl:'Starten', en:'Start', et:'Alusta', fi:'Aloita', fr:'Démarrer', de:'Start', el:'Έναρξη', hu:'Indítás', ga:'Tosaigh', it:'Avvia', lv:'Sākt', lt:'Pradėti', mt:'Ibda', pl:'Start', pt:'Iniciar', ro:'Start', sk:'Štart', sl:'Začni', es:'Empezar', sv:'Starta' },
  loadSaved: { bg:'Зареди запазено оценяване (JSON)', hr:'Učitaj spremljenu procjenu (JSON)', cs:'Načíst uložené hodnocení (JSON)', da:'Indlæs gemt vurdering (JSON)', nl:'Opgeslagen beoordeling laden (JSON)', en:'Load saved assessment (JSON)', et:'Laadi salvestatud hinnang (JSON)', fi:'Lataa tallennettu arviointi (JSON)', fr:'Charger une évaluation enregistrée (JSON)', de:'Gespeicherten Stand laden (JSON)', el:'Φόρτωση αποθηκευμένης αξιολόγησης (JSON)', hu:'Mentett értékelés betöltése (JSON)', ga:'Lódáil measúnú sábháilte (JSON)', it:'Carica valutazione salvata (JSON)', lv:'Ielādēt saglabāto novērtējumu (JSON)', lt:'Įkelti išsaugotą vertinimą (JSON)', mt:'Illowdja valutazzjoni salvata (JSON)', pl:'Wczytaj zapisaną ocenę (JSON)', pt:'Carregar avaliação guardada (JSON)', ro:'Încarcă evaluarea salvată (JSON)', sk:'Načítať uložené hodnotenie (JSON)', sl:'Naloži shranjeno oceno (JSON)', es:'Cargar evaluación guardada (JSON)', sv:'Läs in sparad bedömning (JSON)' },
  orgProfile: { bg:'Профил на организацията', hr:'Profil organizacije', cs:'Profil organizace', da:'Organisationsprofil', nl:'Organisatieprofiel', en:'Organization profile', et:'Organisatsiooni profiil', fi:'Organisaatioprofiili', fr:'Profil de l\'organisation', de:'Organisationsprofil', el:'Προφίλ οργανισμού', hu:'Szervezeti profil', ga:'Próifíl eagraíochta', it:'Profilo dell\'organizzazione', lv:'Organizācijas profils', lt:'Organizacijos profilis', mt:'Profil tal-organizzazzjoni', pl:'Profil organizacji', pt:'Perfil da organização', ro:'Profilul organizației', sk:'Profil organizácie', sl:'Profil organizacije', es:'Perfil de la organización', sv:'Organisationsprofil' },
  orgProfileHint: { bg:'Тази информация се използва само за приблизителна класификация и никога не се качва никъде.', hr:'Ovi se podaci koriste isključivo za grubu klasifikaciju i nikada se nikamo ne prenose.', cs:'Tyto údaje slouží výhradně k hrubé klasifikaci a nikam se nenahrávají.', da:'Disse oplysninger bruges kun til den grove klassificering og uploades aldrig nogen steder.', nl:'Deze gegevens dienen uitsluitend voor de grove classificatie en worden nergens geüpload.', en:'This information is used only for the rough classification and is never uploaded anywhere.', et:'Seda teavet kasutatakse ainult ligikaudseks klassifitseerimiseks ega laadita kunagi kuhugi üles.', fi:'Näitä tietoja käytetään vain karkeaan luokitteluun, eikä niitä koskaan ladata mihinkään.', fr:'Ces informations servent uniquement à la classification approximative et ne sont jamais téléchargées.', de:'Diese Angaben dienen ausschließlich der groben Einstufung und werden nirgendwo hochgeladen.', el:'Αυτές οι πληροφορίες χρησιμοποιούνται μόνο για τη χονδρική ταξινόμηση και δεν μεταφορτώνονται ποτέ πουθενά.', hu:'Ezek az adatok kizárólag a hozzávetőleges besoroláshoz szükségesek, és sehova nem kerülnek feltöltésre.', ga:'Ní úsáidtear an fhaisnéis seo ach don aicmiú garbh agus ní uaslódáiltear í riamh áit ar bith.', it:'Queste informazioni sono utilizzate solo per la classificazione approssimativa e non vengono mai caricate da nessuna parte.', lv:'Šī informācija tiek izmantota tikai aptuvenai klasifikācijai un nekad netiek augšupielādēta nekur.', lt:'Ši informacija naudojama tik apytiksliam klasifikavimui ir niekada niekur neįkeliama.', mt:'Din l-informazzjoni tintuża biss għall-klassifikazzjoni approssimattiva u qatt ma tiġi kkargata band\'oħra.', pl:'Te dane służą wyłącznie do przybliżonej klasyfikacji i nigdy nie są nigdzie przesyłane.', pt:'Estas informações são usadas apenas para a classificação aproximada e nunca são carregadas para qualquer lugar.', ro:'Aceste informații sunt utilizate doar pentru clasificarea aproximativă și nu sunt niciodată încărcate nicăieri.', sk:'Tieto údaje sa používajú výlučne na hrubú klasifikáciu a nikam sa nenahrávajú.', sl:'Ti podatki se uporabljajo izključno za grobo razvrstitev in se nikoli nikamor ne naložijo.', es:'Esta información se utiliza únicamente para la clasificación aproximada y nunca se sube a ningún lugar.', sv:'Denna information används endast för den grova klassificeringen och laddas aldrig upp någonstans.' },
  orgName: { bg:'Име на организацията (незадължително)', hr:'Naziv organizacije (neobavezno)', cs:'Název organizace (volitelné)', da:'Organisationens navn (valgfrit)', nl:'Naam van de organisatie (optioneel)', en:'Organization name (optional)', et:'Organisatsiooni nimi (valikuline)', fi:'Organisaation nimi (valinnainen)', fr:'Nom de l\'organisation (facultatif)', de:'Name der Organisation (optional)', el:'Όνομα οργανισμού (προαιρετικό)', hu:'Szervezet neve (opcionális)', ga:'Ainm na heagraíochta (roghnach)', it:'Nome dell\'organizzazione (facoltativo)', lv:'Organizācijas nosaukums (izvēles)', lt:'Organizacijos pavadinimas (neprivaloma)', mt:'Isem tal-organizzazzjoni (fakultattiv)', pl:'Nazwa organizacji (opcjonalnie)', pt:'Nome da organização (opcional)', ro:'Numele organizației (opțional)', sk:'Názov organizácie (voliteľné)', sl:'Ime organizacije (neobvezno)', es:'Nombre de la organización (opcional)', sv:'Organisationens namn (valfritt)' },
  orgNamePlaceholder: { bg:'напр. Пример ООД', hr:'npr. Primjer d.o.o.', cs:'např. Příklad s.r.o.', da:'f.eks. Eksempel A/S', nl:'bijv. Voorbeeld B.V.', en:'e.g. Example Ltd.', et:'nt Näide OÜ', fi:'esim. Esimerkki Oy', fr:'p. ex. Exemple SARL', de:'z. B. Muster GmbH', el:'π.χ. Παράδειγμα ΑΕ', hu:'pl. Példa Kft.', ga:'m.sh. Sampla Teo.', it:'ad es. Esempio S.r.l.', lv:'piem. Piemērs SIA', lt:'pvz. Pavyzdys UAB', mt:'p.e. Eżempju Ltd', pl:'np. Przykład Sp. z o.o.', pt:'p. ex. Exemplo Lda.', ro:'de ex. Exemplu SRL', sk:'napr. Príklad s.r.o.', sl:'npr. Primer d.o.o.', es:'p. ej. Ejemplo S.L.', sv:'t.ex. Exempel AB' },
  sector: { bg:'Сектор', hr:'Sektor', cs:'Odvětví', da:'Sektor', nl:'Sector', en:'Sector', et:'Sektor', fi:'Toimiala', fr:'Secteur', de:'Sektor', el:'Τομέας', hu:'Ágazat', ga:'Earnáil', it:'Settore', lv:'Nozare', lt:'Sektorius', mt:'Settur', pl:'Sektor', pt:'Setor', ro:'Sector', sk:'Odvetvie', sl:'Sektor', es:'Sector', sv:'Sektor' },
  pleaseSelect: { bg:'— моля, изберете —', hr:'— odaberite —', cs:'— vyberte prosím —', da:'— vælg venligst —', nl:'— maak een keuze —', en:'— please select —', et:'— palun valige —', fi:'— valitse —', fr:'— veuillez choisir —', de:'— bitte wählen —', el:'— παρακαλώ επιλέξτε —', hu:'— kérjük, válasszon —', ga:'— roghnaigh le do thoil —', it:'— seleziona —', lv:'— lūdzu, izvēlieties —', lt:'— pasirinkite —', mt:'— jekk jogħġbok agħżel —', pl:'— proszę wybrać —', pt:'— selecione —', ro:'— selectați —', sk:'— vyberte, prosím —', sl:'— izberite —', es:'— seleccione —', sv:'— välj —' },
  annexI: { bg:'Приложение I', hr:'Prilog I', cs:'Příloha I', da:'Bilag I', nl:'Bijlage I', en:'Annex I', et:'I lisa', fi:'Liite I', fr:'Annexe I', de:'Anhang I', el:'Παράρτημα I', hu:'I. melléklet', ga:'Iarscríbhinn I', it:'Allegato I', lv:'I pielikums', lt:'I priedas', mt:'Anness I', pl:'Załącznik I', pt:'Anexo I', ro:'Anexa I', sk:'Príloha I', sl:'Priloga I', es:'Anexo I', sv:'Bilaga I' },
  annexII: { bg:'Приложение II', hr:'Prilog II', cs:'Příloha II', da:'Bilag II', nl:'Bijlage II', en:'Annex II', et:'II lisa', fi:'Liite II', fr:'Annexe II', de:'Anhang II', el:'Παράρτημα II', hu:'II. melléklet', ga:'Iarscríbhinn II', it:'Allegato II', lv:'II pielikums', lt:'II priedas', mt:'Anness II', pl:'Załącznik II', pt:'Anexo II', ro:'Anexa II', sk:'Príloha II', sl:'Priloga II', es:'Anexo II', sv:'Bilaga II' },
  employees: { bg:'Брой служители', hr:'Broj zaposlenika', cs:'Počet zaměstnanců', da:'Antal medarbejdere', nl:'Aantal medewerkers', en:'Number of employees', et:'Töötajate arv', fi:'Työntekijöiden määrä', fr:'Nombre de collaborateurs', de:'Anzahl Mitarbeitende', el:'Αριθμός εργαζομένων', hu:'Alkalmazottak száma', ga:'Líon na bhfostaithe', it:'Numero di dipendenti', lv:'Darbinieku skaits', lt:'Darbuotojų skaičius', mt:'Numru ta\' impjegati', pl:'Liczba pracowników', pt:'Número de colaboradores', ro:'Numărul de angajați', sk:'Počet zamestnancov', sl:'Število zaposlenih', es:'Número de empleados', sv:'Antal anställda' },
  empSmall: { bg:'< 50 (микро/малко предприятие)', hr:'< 50 (mikro/malo poduzeće)', cs:'< 50 (mikro/malý podnik)', da:'< 50 (mikro-/lille virksomhed)', nl:'< 50 (micro-/kleine onderneming)', en:'< 50 (micro/small enterprise)', et:'< 50 (mikro-/väikeettevõte)', fi:'< 50 (mikro-/pienyritys)', fr:'< 50 (micro/petite entreprise)', de:'< 50 (Kleinstunternehmen/klein)', el:'< 50 (πολύ μικρή/μικρή επιχείρηση)', hu:'< 50 (mikro-/kisvállalkozás)', ga:'< 50 (micrifhiontar/fiontar beag)', it:'< 50 (micro/piccola impresa)', lv:'< 50 (mikro/mazs uzņēmums)', lt:'< 50 (labai maža/maža įmonė)', mt:'< 50 (mikrointrapriża/impriża żgħira)', pl:'< 50 (mikro/małe przedsiębiorstwo)', pt:'< 50 (micro/pequena empresa)', ro:'< 50 (microîntreprindere/întreprindere mică)', sk:'< 50 (mikro/malý podnik)', sl:'< 50 (mikro/malo podjetje)', es:'< 50 (microempresa/pequeña empresa)', sv:'< 50 (mikro-/litet företag)' },
  empMedium: { bg:'50–249 (средно)', hr:'50–249 (srednje)', cs:'50–249 (střední)', da:'50–249 (mellemstor)', nl:'50–249 (middelgroot)', en:'50–249 (medium)', et:'50–249 (keskmine)', fi:'50–249 (keskisuuri)', fr:'50–249 (moyenne)', de:'50–249 (mittel)', el:'50–249 (μεσαία)', hu:'50–249 (közepes)', ga:'50–249 (meánmhéid)', it:'50–249 (media)', lv:'50–249 (vidējs)', lt:'50–249 (vidutinis)', mt:'50–249 (medju)', pl:'50–249 (średnie)', pt:'50–249 (média)', ro:'50–249 (medie)', sk:'50–249 (stredný)', sl:'50–249 (srednje)', es:'50–249 (mediana)', sv:'50–249 (medelstort)' },
  empLarge: { bg:'≥ 250 (голямо)', hr:'≥ 250 (veliko)', cs:'≥ 250 (velký)', da:'≥ 250 (stor)', nl:'≥ 250 (groot)', en:'≥ 250 (large)', et:'≥ 250 (suur)', fi:'≥ 250 (suuri)', fr:'≥ 250 (grande)', de:'≥ 250 (groß)', el:'≥ 250 (μεγάλη)', hu:'≥ 250 (nagy)', ga:'≥ 250 (mór)', it:'≥ 250 (grande)', lv:'≥ 250 (liels)', lt:'≥ 250 (didelis)', mt:'≥ 250 (kbir)', pl:'≥ 250 (duże)', pt:'≥ 250 (grande)', ro:'≥ 250 (mare)', sk:'≥ 250 (veľký)', sl:'≥ 250 (veliko)', es:'≥ 250 (grande)', sv:'≥ 250 (stort)' },
  country: { bg:'Държава', hr:'Zemlja', cs:'Země', da:'Land', nl:'Land', en:'Country', et:'Riik', fi:'Maa', fr:'Pays', de:'Land', el:'Χώρα', hu:'Ország', ga:'Tír', it:'Paese', lv:'Valsts', lt:'Šalis', mt:'Pajjiż', pl:'Kraj', pt:'País', ro:'Țară', sk:'Krajina', sl:'Država', es:'País', sv:'Land' },
  back: { bg:'Назад', hr:'Natrag', cs:'Zpět', da:'Tilbage', nl:'Terug', en:'Back', et:'Tagasi', fi:'Takaisin', fr:'Retour', de:'Zurück', el:'Πίσω', hu:'Vissza', ga:'Ar ais', it:'Indietro', lv:'Atpakaļ', lt:'Atgal', mt:'Lura', pl:'Wstecz', pt:'Voltar', ro:'Înapoi', sk:'Späť', sl:'Nazaj', es:'Atrás', sv:'Tillbaka' },
  next: { bg:'Напред', hr:'Dalje', cs:'Další', da:'Næste', nl:'Volgende', en:'Next', et:'Edasi', fi:'Seuraava', fr:'Suivant', de:'Weiter', el:'Επόμενο', hu:'Következő', ga:'Ar aghaidh', it:'Avanti', lv:'Tālāk', lt:'Toliau', mt:'Li Jmiss', pl:'Dalej', pt:'Seguinte', ro:'Următorul', sk:'Ďalej', sl:'Naprej', es:'Siguiente', sv:'Nästa' },
  toResults: { bg:'Към резултатите', hr:'Na rezultate', cs:'K výsledkům', da:'Til resultaterne', nl:'Naar de resultaten', en:'To the results', et:'Tulemuste juurde', fi:'Tuloksiin', fr:'Vers les résultats', de:'Zu den Ergebnissen', el:'Στα αποτελέσματα', hu:'Az eredményekhez', ga:'Chuig na torthaí', it:'Ai risultati', lv:'Uz rezultātiem', lt:'Į rezultatus', mt:'Għar-riżultati', pl:'Do wyników', pt:'Para os resultados', ro:'La rezultate', sk:'K výsledkom', sl:'K rezultatom', es:'A los resultados', sv:'Till resultaten' },
  backToQuestions: { bg:'Обратно към въпросите', hr:'Natrag na pitanja', cs:'Zpět na otázky', da:'Tilbage til spørgsmålene', nl:'Terug naar de vragen', en:'Back to the questions', et:'Tagasi küsimuste juurde', fi:'Takaisin kysymyksiin', fr:'Retour aux questions', de:'Zurück zu den Fragen', el:'Πίσω στις ερωτήσεις', hu:'Vissza a kérdésekhez', ga:'Ar ais chuig na ceisteanna', it:'Torna alle domande', lv:'Atpakaļ pie jautājumiem', lt:'Atgal į klausimus', mt:'Lura għall-mistoqsijiet', pl:'Powrót do pytań', pt:'Voltar às perguntas', ro:'Înapoi la întrebări', sk:'Späť na otázky', sl:'Nazaj na vprašanja', es:'Volver a las preguntas', sv:'Tillbaka till frågorna' },
  exportJsonBtn: { bg:'Експортиране на JSON', hr:'Izvezi JSON', cs:'Exportovat JSON', da:'Eksportér JSON', nl:'JSON exporteren', en:'Export JSON', et:'Ekspordi JSON', fi:'Vie JSON', fr:'Exporter en JSON', de:'JSON exportieren', el:'Εξαγωγή JSON', hu:'JSON exportálása', ga:'Easpórtáil JSON', it:'Esporta JSON', lv:'Eksportēt JSON', lt:'Eksportuoti JSON', mt:'Esporta JSON', pl:'Eksportuj JSON', pt:'Exportar JSON', ro:'Exportă JSON', sk:'Exportovať JSON', sl:'Izvozi JSON', es:'Exportar JSON', sv:'Exportera JSON' },
  printPdf: { bg:'Печат като PDF', hr:'Ispiši kao PDF', cs:'Vytisknout jako PDF', da:'Udskriv som PDF', nl:'Afdrukken als PDF', en:'Print as PDF', et:'Prindi PDF-ina', fi:'Tulosta PDF:nä', fr:'Imprimer en PDF', de:'Als PDF drucken', el:'Εκτύπωση ως PDF', hu:'Nyomtatás PDF-ként', ga:'Priontáil mar PDF', it:'Stampa come PDF', lv:'Drukāt kā PDF', lt:'Spausdinti kaip PDF', mt:'Ipprintja bħala PDF', pl:'Drukuj jako PDF', pt:'Imprimir como PDF', ro:'Tipărește ca PDF', sk:'Vytlačiť ako PDF', sl:'Natisni kot PDF', es:'Imprimir como PDF', sv:'Skriv ut som PDF' },
  resetAll: { bg:'Нулиране на всичко', hr:'Poništi sve', cs:'Resetovat vše', da:'Nulstil alt', nl:'Alles resetten', en:'Reset everything', et:'Lähtesta kõik', fi:'Nollaa kaikki', fr:'Tout réinitialiser', de:'Alles zurücksetzen', el:'Επαναφορά όλων', hu:'Minden visszaállítása', ga:'Athshocraigh gach rud', it:'Reimposta tutto', lv:'Atiestatīt visu', lt:'Nustatyti viską iš naujo', mt:'Irrisettja kollox', pl:'Zresetuj wszystko', pt:'Repor tudo', ro:'Resetează tot', sk:'Resetovať všetko', sl:'Ponastavi vse', es:'Restablecer todo', sv:'Återställ allt' },
  resetConfirm: { bg:'Наистина ли да се изтрият всички въведени данни? Това не може да бъде отменено.', hr:'Stvarno izbrisati sve unose? To se ne može poništiti.', cs:'Opravdu smazat všechny zadané údaje? Tuto akci nelze vrátit zpět.', da:'Vil du virkelig slette alle indtastninger? Dette kan ikke fortrydes.', nl:'Alle invoer echt verwijderen? Dit kan niet ongedaan worden gemaakt.', en:'Really delete all entries? This cannot be undone.', et:'Kas kustutada tõesti kõik sisestused? Seda ei saa tagasi võtta.', fi:'Poistetaanko kaikki syötteet varmasti? Tätä ei voi perua.', fr:'Vraiment supprimer toutes les saisies ? Cette action est irréversible.', de:'Wirklich alle Eingaben löschen? Das kann nicht rückgängig gemacht werden.', el:'Θέλετε πραγματικά να διαγράψετε όλες τις καταχωρίσεις; Αυτό δεν μπορεί να αναιρεθεί.', hu:'Valóban törli az összes bejegyzést? Ez nem vonható vissza.', ga:'An bhfuil tú cinnte gur mian leat gach iontráil a scriosadh? Ní féidir é seo a chur ar ais.', it:'Eliminare davvero tutte le voci? Questa azione non può essere annullata.', lv:'Vai tiešām dzēst visus ierakstus? To nevar atsaukt.', lt:'Ar tikrai ištrinti visus įrašus? Šio veiksmo anuliuoti negalima.', mt:'Tabilħaqq tħassar l-entrati kollha? Dan ma jistax jitreġġa\' lura.', pl:'Czy na pewno usunąć wszystkie wpisy? Tej operacji nie można cofnąć.', pt:'Eliminar mesmo todas as entradas? Esta ação não pode ser anulada.', ro:'Ștergeți într-adevăr toate intrările? Această acțiune nu poate fi anulată.', sk:'Naozaj vymazať všetky záznamy? Túto akciu nemožno vrátiť späť.', sl:'Ali res želite izbrisati vse vnose? Tega dejanja ni mogoče razveljaviti.', es:'¿Eliminar realmente todas las entradas? Esta acción no se puede deshacer.', sv:'Vill du verkligen radera alla poster? Detta kan inte ångras.' },
  importError: { bg:'Файлът не можа да бъде прочетен — валиден ли е JSON файл на nis2-quickcheck?', hr:'Datoteku nije bilo moguće pročitati — je li riječ o valjanoj nis2-quickcheck JSON datoteci?', cs:'Soubor se nepodařilo přečíst — jde o platný soubor JSON nis2-quickcheck?', da:'Filen kunne ikke læses — er det en gyldig nis2-quickcheck JSON-fil?', nl:'Bestand kon niet worden gelezen — is het een geldig nis2-quickcheck JSON-bestand?', en:'Could not read the file — is it a valid nis2-quickcheck JSON file?', et:'Faili ei õnnestunud lugeda — kas see on kehtiv nis2-quickcheck JSON-fail?', fi:'Tiedostoa ei voitu lukea — onko se kelvollinen nis2-quickcheck JSON-tiedosto?', fr:'Impossible de lire le fichier — s\'agit-il d\'un fichier JSON nis2-quickcheck valide ?', de:'Datei konnte nicht gelesen werden — ist es eine gültige nis2-quickcheck-JSON-Datei?', el:'Δεν ήταν δυνατή η ανάγνωση του αρχείου — είναι έγκυρο αρχείο JSON nis2-quickcheck;', hu:'A fájlt nem sikerült beolvasni — érvényes nis2-quickcheck JSON-fájl?', ga:'Níorbh fhéidir an comhad a léamh — an comhad bailí JSON nis2-quickcheck é?', it:'Impossibile leggere il file — è un file JSON nis2-quickcheck valido?', lv:'Neizdevās nolasīt failu — vai tas ir derīgs nis2-quickcheck JSON fails?', lt:'Nepavyko nuskaityti failo — ar tai galiojantis nis2-quickcheck JSON failas?', mt:'Ma setax jinqara l-fajl — huwa fajl JSON nis2-quickcheck validu?', pl:'Nie udało się odczytać pliku — czy to prawidłowy plik JSON nis2-quickcheck?', pt:'Não foi possível ler o ficheiro — é um ficheiro JSON nis2-quickcheck válido?', ro:'Fișierul nu a putut fi citit — este un fișier JSON nis2-quickcheck valid?', sk:'Súbor sa nepodarilo prečítať — ide o platný súbor JSON nis2-quickcheck?', sl:'Datoteke ni bilo mogoče prebrati — ali gre za veljavno datoteko JSON nis2-quickcheck?', es:'No se pudo leer el archivo — ¿es un archivo JSON de nis2-quickcheck válido?', sv:'Filen kunde inte läsas — är det en giltig nis2-quickcheck JSON-fil?' },
  notePlaceholder: { bg:'Бележка (незадължително)', hr:'Bilješka (neobavezno)', cs:'Poznámka (volitelné)', da:'Note (valgfrit)', nl:'Notitie (optioneel)', en:'Note (optional)', et:'Märkus (valikuline)', fi:'Muistiinpano (valinnainen)', fr:'Note (facultatif)', de:'Notiz (optional)', el:'Σημείωση (προαιρετικό)', hu:'Megjegyzés (opcionális)', ga:'Nóta (roghnach)', it:'Nota (facoltativo)', lv:'Piezīme (izvēles)', lt:'Pastaba (neprivaloma)', mt:'Nota (fakultattiv)', pl:'Notatka (opcjonalnie)', pt:'Nota (opcional)', ro:'Notă (opțional)', sk:'Poznámka (voliteľné)', sl:'Opomba (neobvezno)', es:'Nota (opcional)', sv:'Anteckning (valfritt)' },
  results: { bg:'📊 Табло с резултати', hr:'📊 Nadzorna ploča rezultata', cs:'📊 Panel výsledků', da:'📊 Resultatdashboard', nl:'📊 Resultatendashboard', en:'📊 Result dashboard', et:'📊 Tulemuste töölaud', fi:'📊 Tulostaulu', fr:'📊 Tableau de bord des résultats', de:'📊 Ergebnis-Dashboard', el:'📊 Πίνακας αποτελεσμάτων', hu:'📊 Eredménypanel', ga:'📊 Painéal torthaí', it:'📊 Cruscotto dei risultati', lv:'📊 Rezultātu panelis', lt:'📊 Rezultatų skydelis', mt:'📊 Dashboard tar-riżultati', pl:'📊 Panel wyników', pt:'📊 Painel de resultados', ro:'📊 Tabloul de bord al rezultatelor', sk:'📊 Panel výsledkov', sl:'📊 Nadzorna plošča rezultatov', es:'📊 Panel de resultados', sv:'📊 Resultatpanel' },
  questionsAnswered: { bg:'въпроса отговорени', hr:'pitanja odgovorena', cs:'otázek zodpovězeno', da:'spørgsmål besvaret', nl:'vragen beantwoord', en:'questions answered', et:'küsimusele vastatud', fi:'kysymykseen vastattu', fr:'questions répondues', de:'Fragen beantwortet', el:'ερωτήσεις απαντήθηκαν', hu:'kérdés megválaszolva', ga:'ceist freagraithe', it:'domande risposte', lv:'jautājumi atbildēti', lt:'klausimai atsakyti', mt:'mistoqsijiet imwieġba', pl:'pytań odpowiedziano', pt:'perguntas respondidas', ro:'întrebări la care s-a răspuns', sk:'otázok zodpovedaných', sl:'vprašanj odgovorjenih', es:'preguntas respondidas', sv:'frågor besvarade' },
  overallMaturity: { bg:'Обща зрялост', hr:'Ukupna zrelost', cs:'Celková zralost', da:'Samlet modenhed', nl:'Totale volwassenheid', en:'Overall maturity', et:'Üldine küpsus', fi:'Kokonaiskypsyys', fr:'Maturité globale', de:'Gesamt-Reifegrad', el:'Συνολική ωριμότητα', hu:'Teljes érettség', ga:'Aibíocht fhoriomlán', it:'Maturità complessiva', lv:'Vispārējais briedums', lt:'Bendras brandumas', mt:'Maturità ġenerali', pl:'Ogólna dojrzałość', pt:'Maturidade global', ro:'Maturitate globală', sk:'Celková zrelosť', sl:'Skupna zrelost', es:'Madurez global', sv:'Övergripande mognad' },
  classificationLabel: { bg:'Приблизителна класификация (незадължителна)', hr:'Gruba klasifikacija (neobvezujuća)', cs:'Hrubá klasifikace (nezávazná)', da:'Grov klassificering (ikke-bindende)', nl:'Grove classificatie (vrijblijvend)', en:'Rough classification (non-binding)', et:'Ligikaudne klassifikatsioon (mittesiduv)', fi:'Karkea luokittelu (ei sitova)', fr:'Classification approximative (non contraignante)', de:'Grobe Einstufung (unverbindlich)', el:'Χονδρική ταξινόμηση (μη δεσμευτική)', hu:'Hozzávetőleges besorolás (nem kötelező érvényű)', ga:'Aicmiú garbh (neamhcheangailteach)', it:'Classificazione approssimativa (non vincolante)', lv:'Aptuvena klasifikācija (nesaistoša)', lt:'Apytikslis klasifikavimas (neįpareigojantis)', mt:'Klassifikazzjoni approssimattiva (mhux vinkolanti)', pl:'Przybliżona klasyfikacja (niewiążąca)', pt:'Classificação aproximada (não vinculativa)', ro:'Clasificare aproximativă (neobligatorie)', sk:'Hrubá klasifikácia (nezáväzná)', sl:'Groba razvrstitev (nezavezujoča)', es:'Clasificación aproximada (no vinculante)', sv:'Grov klassificering (icke-bindande)' },
  maturityByDomain: { bg:'Зрялост по област', hr:'Zrelost po domeni', cs:'Zralost podle domény', da:'Modenhed pr. domæne', nl:'Volwassenheid per domein', en:'Maturity by domain', et:'Küpsus valdkonniti', fi:'Kypsyys osa-alueittain', fr:'Maturité par domaine', de:'Reifegrad je Domäne', el:'Ωριμότητα ανά τομέα', hu:'Érettség terület szerint', ga:'Aibíocht de réir réimse', it:'Maturità per dominio', lv:'Briedums pa jomām', lt:'Brandumas pagal sritį', mt:'Maturità skont il-qasam', pl:'Dojrzałość według domeny', pt:'Maturidade por domínio', ro:'Maturitate pe domeniu', sk:'Zrelosť podľa domény', sl:'Zrelost po domeni', es:'Madurez por dominio', sv:'Mognad per domän' },
  radarView: { bg:'Радарен изглед', hr:'Radarski prikaz', cs:'Paprskový pohled', da:'Radarvisning', nl:'Radarweergave', en:'Radar view', et:'Radarvaade', fi:'Tutkanäkymä', fr:'Vue radar', de:'Radar-Ansicht', el:'Προβολή ραντάρ', hu:'Radarnézet', ga:'Amharc radair', it:'Vista radar', lv:'Radara skats', lt:'Radaro vaizdas', mt:'Vista radar', pl:'Widok radarowy', pt:'Vista radar', ro:'Vizualizare radar', sk:'Radarový pohľad', sl:'Radarski pogled', es:'Vista radar', sv:'Radarvy' },
  gapAnalysis: { bg:'Анализ на пропуските', hr:'Analiza nedostataka', cs:'Analýza mezer', da:'Gap-analyse', nl:'Gap-analyse', en:'Gap analysis', et:'Lõhede analüüs', fi:'Kuiluanalyysi', fr:'Analyse des écarts', de:'Gap-Analyse', el:'Ανάλυση κενών', hu:'Hiányelemzés', ga:'Anailís bearna', it:'Analisi dei divari', lv:'Atšķirību analīze', lt:'Spragų analizė', mt:'Analiżi tal-lakuni', pl:'Analiza luk', pt:'Análise de lacunas', ro:'Analiza decalajelor', sk:'Analýza medzier', sl:'Analiza vrzeli', es:'Análisis de brechas', sv:'Gapanalys' },
  countryInfo: { bg:'Информация за държавата', hr:'Informacije o zemlji', cs:'Informace o zemi', da:'Landeoplysninger', nl:'Landinformatie', en:'Country information', et:'Riigi teave', fi:'Maan tiedot', fr:'Informations pays', de:'Länderinformation', el:'Πληροφορίες χώρας', hu:'Országadatok', ga:'Faisnéis tíre', it:'Informazioni sul paese', lv:'Valsts informācija', lt:'Šalies informacija', mt:'Informazzjoni dwar il-pajjiż', pl:'Informacje o kraju', pt:'Informações do país', ro:'Informații despre țară', sk:'Informácie o krajine', sl:'Informacije o državi', es:'Información del país', sv:'Landinformation' },
  colDomain: { bg:'Област', hr:'Domena', cs:'Doména', da:'Domæne', nl:'Domein', en:'Domain', et:'Valdkond', fi:'Osa-alue', fr:'Domaine', de:'Domäne', el:'Τομέας', hu:'Terület', ga:'Réimse', it:'Dominio', lv:'Joma', lt:'Sritis', mt:'Qasam', pl:'Domena', pt:'Domínio', ro:'Domeniu', sk:'Doména', sl:'Domena', es:'Dominio', sv:'Domän' },
  colMaturity: { bg:'Зрялост', hr:'Zrelost', cs:'Zralost', da:'Modenhed', nl:'Volwassenheid', en:'Maturity', et:'Küpsus', fi:'Kypsyys', fr:'Maturité', de:'Reifegrad', el:'Ωριμότητα', hu:'Érettség', ga:'Aibíocht', it:'Maturità', lv:'Briedums', lt:'Brandumas', mt:'Maturità', pl:'Dojrzałość', pt:'Maturidade', ro:'Maturitate', sk:'Zrelosť', sl:'Zrelost', es:'Madurez', sv:'Mognad' },
  colTarget: { bg:'Цел', hr:'Cilj', cs:'Cíl', da:'Mål', nl:'Doel', en:'Target', et:'Eesmärk', fi:'Tavoite', fr:'Cible', de:'Ziel', el:'Στόχος', hu:'Cél', ga:'Sprioc', it:'Obiettivo', lv:'Mērķis', lt:'Tikslas', mt:'Mira', pl:'Cel', pt:'Objetivo', ro:'Țintă', sk:'Cieľ', sl:'Cilj', es:'Objetivo', sv:'Mål' },
  colGap: { bg:'Пропуск', hr:'Nedostatak', cs:'Mezera', da:'Gab', nl:'Verschil', en:'Gap', et:'Lõhe', fi:'Kuilu', fr:'Écart', de:'Lücke', el:'Κενό', hu:'Hiány', ga:'Bearna', it:'Divario', lv:'Atšķirība', lt:'Spraga', mt:'Lakuna', pl:'Luka', pt:'Lacuna', ro:'Decalaj', sk:'Medzera', sl:'Vrzel', es:'Brecha', sv:'Gap' },
  colPriority: { bg:'Приоритет', hr:'Prioritet', cs:'Priorita', da:'Prioritet', nl:'Prioriteit', en:'Priority', et:'Prioriteet', fi:'Prioriteetti', fr:'Priorité', de:'Priorität', el:'Προτεραιότητα', hu:'Prioritás', ga:'Tosaíocht', it:'Priorità', lv:'Prioritāte', lt:'Prioritetas', mt:'Prijorità', pl:'Priorytet', pt:'Prioridade', ro:'Prioritate', sk:'Priorita', sl:'Prioriteta', es:'Prioridad', sv:'Prioritet' },
  authorityLabel: { bg:'Компетентен орган', hr:'Nadležno tijelo', cs:'Příslušný orgán', da:'Kompetent myndighed', nl:'Bevoegde autoriteit', en:'Competent authority', et:'Pädev asutus', fi:'Toimivaltainen viranomainen', fr:'Autorité compétente', de:'Zuständige Behörde', el:'Αρμόδια αρχή', hu:'Illetékes hatóság', ga:'Údarás inniúil', it:'Autorità competente', lv:'Kompetentā iestāde', lt:'Kompetentinga institucija', mt:'Awtorità kompetenti', pl:'Właściwy organ', pt:'Autoridade competente', ro:'Autoritate competentă', sk:'Príslušný orgán', sl:'Pristojni organ', es:'Autoridad competente', sv:'Behörig myndighet' },
  lawLabel: { bg:'Национален закон', hr:'Nacionalni zakon', cs:'Vnitrostátní zákon', da:'National lov', nl:'Nationale wet', en:'National law', et:'Riiklik seadus', fi:'Kansallinen laki', fr:'Loi nationale', de:'Nationales Gesetz', el:'Εθνικός νόμος', hu:'Nemzeti jogszabály', ga:'Dlí náisiúnta', it:'Legge nazionale', lv:'Valsts likums', lt:'Nacionalinis įstatymas', mt:'Liġi nazzjonali', pl:'Ustawa krajowa', pt:'Lei nacional', ro:'Lege națională', sk:'Vnútroštátny zákon', sl:'Nacionalni zakon', es:'Ley nacional', sv:'Nationell lag' },
  statusLabel: { bg:'Статус на транспониране', hr:'Status transpozicije', cs:'Stav transpozice', da:'Gennemførelsesstatus', nl:'Omzettingsstatus', en:'Transposition status', et:'Ülevõtmise staatus', fi:'Täytäntöönpanotilanne', fr:'État de transposition', de:'Umsetzungsstand', el:'Κατάσταση μεταφοράς', hu:'Átültetési állapot', ga:'Stádas trasuite', it:'Stato di recepimento', lv:'Transponēšanas statuss', lt:'Perkėlimo statusas', mt:'Status ta\' traspożizzjoni', pl:'Stan transpozycji', pt:'Estado de transposição', ro:'Stadiul transpunerii', sk:'Stav transpozície', sl:'Stanje prenosa', es:'Estado de transposición', sv:'Genomförandestatus' },
  csirtLabel: { bg:'CSIRT', hr:'CSIRT', cs:'CSIRT', da:'CSIRT', nl:'CSIRT', en:'CSIRT', et:'CSIRT', fi:'CSIRT', fr:'CSIRT', de:'CSIRT', el:'CSIRT', hu:'CSIRT', ga:'CSIRT', it:'CSIRT', lv:'CSIRT', lt:'CSIRT', mt:'CSIRT', pl:'CSIRT', pt:'CSIRT', ro:'CSIRT', sk:'CSIRT', sl:'CSIRT', es:'CSIRT', sv:'CSIRT' },
  penaltyEssential: { bg:'Диапазон на санкциите (съществени субекти)', hr:'Raspon sankcija (ključni subjekti)', cs:'Rozsah sankcí (zásadní subjekty)', da:'Sanktionsniveau (væsentlige enheder)', nl:'Boetebandbreedte (essentiële entiteiten)', en:'Penalty range (essential entities)', et:'Karistuste vahemik (olulised üksused)', fi:'Seuraamusten vaihteluväli (keskeiset toimijat)', fr:'Fourchette de sanctions (entités essentielles)', de:'Bußgeldrahmen (wesentliche E.)', el:'Εύρος κυρώσεων (βασικές οντότητες)', hu:'Bírságsáv (alapvető szervezetek)', ga:'Raon pionóis (eintitis riachtanacha)', it:'Intervallo sanzionatorio (soggetti essenziali)', lv:'Sodu diapazons (būtiskās vienības)', lt:'Baudų diapazonas (esminiai subjektai)', mt:'Firxa ta\' penali (entitajiet essenzjali)', pl:'Zakres kar (podmioty kluczowe)', pt:'Intervalo de sanções (entidades essenciais)', ro:'Interval de sancțiuni (entități esențiale)', sk:'Rozsah pokút (kľúčové subjekty)', sl:'Razpon kazni (bistveni subjekti)', es:'Rango de sanciones (entidades esenciales)', sv:'Sanktionsintervall (väsentliga enheter)' },
  penaltyImportant: { bg:'Диапазон на санкциите (важни субекти)', hr:'Raspon sankcija (važni subjekti)', cs:'Rozsah sankcí (důležité subjekty)', da:'Sanktionsniveau (vigtige enheder)', nl:'Boetebandbreedte (belangrijke entiteiten)', en:'Penalty range (important entities)', et:'Karistuste vahemik (tähtsad üksused)', fi:'Seuraamusten vaihteluväli (tärkeät toimijat)', fr:'Fourchette de sanctions (entités importantes)', de:'Bußgeldrahmen (wichtige E.)', el:'Εύρος κυρώσεων (σημαντικές οντότητες)', hu:'Bírságsáv (fontos szervezetek)', ga:'Raon pionóis (eintitis thábhachtacha)', it:'Intervallo sanzionatorio (soggetti importanti)', lv:'Sodu diapazons (svarīgās vienības)', lt:'Baudų diapazonas (svarbūs subjektai)', mt:'Firxa ta\' penali (entitajiet importanti)', pl:'Zakres kar (podmioty ważne)', pt:'Intervalo de sanções (entidades importantes)', ro:'Interval de sancțiuni (entități importante)', sk:'Rozsah pokút (dôležité subjekty)', sl:'Razpon kazni (pomembni subjekti)', es:'Rango de sanciones (entidades importantes)', sv:'Sanktionsintervall (viktiga enheter)' },
  noteLabel: { bg:'Забележка', hr:'Napomena', cs:'Poznámka', da:'Bemærkning', nl:'Opmerking', en:'Note', et:'Märkus', fi:'Huomautus', fr:'Remarque', de:'Hinweis', el:'Σημείωση', hu:'Megjegyzés', ga:'Nóta', it:'Nota', lv:'Piezīme', lt:'Pastaba', mt:'Nota', pl:'Uwaga', pt:'Nota', ro:'Notă', sk:'Poznámka', sl:'Opomba', es:'Nota', sv:'Anmärkning' },
  langUnavailable: { bg:'', hr:'', cs:'', da:'', nl:'', en:'', et:'', fi:'', fr:'', de:'', el:'', hu:'', ga:'', it:'', lv:'', lt:'', mt:'', pl:'', pt:'', ro:'', sk:'', sl:'', es:'', sv:'' },
  prioCritical: { bg:'Критичен', hr:'Kritično', cs:'Kritická', da:'Kritisk', nl:'Kritiek', en:'Critical', et:'Kriitiline', fi:'Kriittinen', fr:'Critique', de:'Kritisch', el:'Κρίσιμη', hu:'Kritikus', ga:'Criticiúil', it:'Critica', lv:'Kritisks', lt:'Kritinis', mt:'Kritiku', pl:'Krytyczny', pt:'Crítica', ro:'Critic', sk:'Kritická', sl:'Kritično', es:'Crítica', sv:'Kritisk' },
  prioHigh: { bg:'Висок', hr:'Visoko', cs:'Vysoká', da:'Høj', nl:'Hoog', en:'High', et:'Kõrge', fi:'Korkea', fr:'Élevée', de:'Hoch', el:'Υψηλή', hu:'Magas', ga:'Ard', it:'Alta', lv:'Augsts', lt:'Aukštas', mt:'Għoli', pl:'Wysoki', pt:'Alta', ro:'Ridicat', sk:'Vysoká', sl:'Visoka', es:'Alta', sv:'Hög' },
  prioMedium: { bg:'Среден', hr:'Srednje', cs:'Střední', da:'Middel', nl:'Gemiddeld', en:'Medium', et:'Keskmine', fi:'Keskitaso', fr:'Moyenne', de:'Mittel', el:'Μεσαία', hu:'Közepes', ga:'Meánach', it:'Media', lv:'Vidējs', lt:'Vidutinis', mt:'Medju', pl:'Średni', pt:'Média', ro:'Mediu', sk:'Stredná', sl:'Srednja', es:'Media', sv:'Medel' },
  prioLow: { bg:'Нисък', hr:'Nisko', cs:'Nízká', da:'Lav', nl:'Laag', en:'Low', et:'Madal', fi:'Matala', fr:'Faible', de:'Niedrig', el:'Χαμηλή', hu:'Alacsony', ga:'Íseal', it:'Bassa', lv:'Zems', lt:'Žemas', mt:'Baxx', pl:'Niski', pt:'Baixa', ro:'Scăzut', sk:'Nízka', sl:'Nizka', es:'Baja', sv:'Låg' },
};

let currentLang = localStorage.getItem('nis2qc_lang') || (navigator.language || 'en').slice(0, 2);
if (!LANGUAGES.some(l => l.code === currentLang)) currentLang = 'en';

function setLang(code) {
  currentLang = code;
  localStorage.setItem('nis2qc_lang', code);
  render();
}

// t(): UI-String übersetzen, Fallback auf Englisch, dann auf den Key selbst.
function t(key) {
  const entry = UI[key];
  if (!entry) return key;
  return entry[currentLang] || entry.en || key;
}

// tl(): lokalisierbares Datenfeld übersetzen ({de:'', en:'', ...}), Fallback Englisch/Deutsch.
function tl(field) {
  if (field === null || field === undefined) return '';
  if (typeof field === 'string') return field; // nicht-lokalisierte Felder (z.B. Eigennamen)
  return field[currentLang] || field.en || field.de || '';
}
